=== lortas/Earthdawn-Character-Editor/config/earthdawndiscipline.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/discipline" xmlns="http://earthdawn.com/discipline" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="DISCIPLINEDURABILITY_type">
		<xs:attribute name="value" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="death" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="unconsciousness" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="circle" type="edt:unsigned_int" default="0"/>
	</xs:complexType>
	<xs:complexType name="DISCIPLINESPELL_type">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="edt:spellkind_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="FOREIGNTALENTS_type">
		<xs:attribute name="maxcircle" type="edt:circle_type" default="1"/>
		<xs:attribute name="mincircle" type="edt:circle_type" default="1"/>
	</xs:complexType>
	<xs:complexType name="DISCIPLINECIRCLE_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element minOccurs="0" maxOccurs="1" name="FOREIGNTALENTS" type="FOREIGNTALENTS_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="OPTIONALTALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="FREETALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="8" name="DISCIPLINETALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="1" maxOccurs="1" name="TALENTABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELL" type="DISCIPLINESPELL_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELLABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="DEFENSE" type="edt:DEFENSEABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="INITIATIVE" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTEST" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMA" type="edt:KARMAABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMASTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ABILITY" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="DISCIPLINE">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element minOccurs="1" maxOccurs="1" name="DURABILITY" type="DISCIPLINEDURABILITY_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="EASYSKILL" type="xs:string"/>
				<xs:element minOccurs="8" maxOccurs="15" name="CIRCLE" type="DISCIPLINECIRCLE_type"/>
				<xs:element minOccurs="0" maxOccurs="1" name="KARMARITUAL" type="xs:string"/>
				<xs:element minOccurs="0" maxOccurs="1" name="HALFMAGIC" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="bookref" type="xs:string" default=""/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED3"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED3en/Sorcerer.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Sorcerer" lang="en" bookref="CPG p.65" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="4" unconsciousness="3"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Claw Shape"/>
		<OPTIONALTALENT name="Haggle"/>
		<OPTIONALTALENT name="Impress"/>
		<OPTIONALTALENT name="Search"/>
		<OPTIONALTALENT name="Spell Matrix" limitation="S2"/>
		<DISCIPLINETALENT name="Evaluate"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Read/Write Magic"/>
		<DISCIPLINETALENT name="Spellcasting"/>
		<DISCIPLINETALENT name="Spell Matrix" limitation="S1"/>
		<DISCIPLINETALENT name="Thread Weaving" limitation="Sorcery"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Assuring Touch"/>
		<SPELL type="sorcery" name="Astral Sense"/>
		<SPELL type="sorcery" name="Blessing of the Giant"/>
		<SPELL type="sorcery" name="Cobra Charms the Weasel"/>
		<SPELL type="sorcery" name="Dispel Magic"/>
		<SPELL type="sorcery" name="Dry and Wet"/>
		<SPELL type="sorcery" name="Earth Darts"/>
		<SPELL type="sorcery" name="Heat Food"/>
		<SPELL type="sorcery" name="Light"/>
		<SPELL type="sorcery" name="Monkey Pretends to be Tiger"/>
		<SPELL type="sorcery" name="Purify Water"/>
		<SPELL type="sorcery" name="Shanjo Writes with Air"/>
		<SPELL type="sorcery" name="Sun Shrinks the Petal"/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Abate Curse"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="First Impression"/>
		<OPTIONALTALENT name="Flame Arrow"/>
		<OPTIONALTALENT name="Item History"/>
		<OPTIONALTALENT name="Picking Pockets"/>
		<OPTIONALTALENT name="Research"/>
		<OPTIONALTALENT name="Spell Matrix" limitation="S3"/>
		<DISCIPLINETALENT name="Astral Sight"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Astral Shield"/>
		<SPELL type="sorcery" name="Boil Water"/>
		<SPELL type="sorcery" name="Clean"/>
		<SPELL type="sorcery" name="Dragon’s Nose Smells Magic"/>
		<SPELL type="sorcery" name="Ignite"/>
		<SPELL type="sorcery" name="Sterilize Object"/>
		<SPELL type="sorcery" name="The Thousand Faces of Cheung"/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Arcane Mutterings"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Alarm"/>
		<SPELL type="sorcery" name="Astral Strike"/>
		<SPELL type="sorcery" name="Dragon Returns to His Lair"/>
		<SPELL type="sorcery" name="Emperor Eats Rotten Shellfish"/>
		<SPELL type="sorcery" name="Levitate"/>
		<SPELL type="sorcery" name="Monk Slaps the Water"/>
		<SPELL type="sorcery" name="Old Man Wears Shoe on Hand"/>
		<SPELL type="sorcery" name="Plant Feast"/>
		<SPELL type="sorcery" name="Puddle Deep"/>
		<SPELL type="sorcery" name="Repair"/>
		<SPELL type="sorcery" name="Rust"/>
		<SPELL type="sorcery" name="Shatter Lock"/>
		<SPELL type="sorcery" name="The Fog of Con-Sha"/>
		<SPELLABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Enduring Art"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Buoyancy"/>
		<SPELL type="sorcery" name="Dragon Brings Rain"/>
		<SPELL type="sorcery" name="Dragon’s Tongue Licks Palm"/>
		<SPELL type="sorcery" name="Falcon’s Cloak"/>
		<SPELL type="sorcery" name="Fatal Food"/>
		<SPELL type="sorcery" name="Infant Opens and Closes Its Eyes"/>
		<SPELL type="sorcery" name="Liquid Arrow"/>
		<SPELL type="sorcery" name="Princess Dreams of Lotus Flowers"/>
		<SPELL type="sorcery" name="The Grip of Chi"/>
		<SPELL type="sorcery" name="The Hand of Chi"/>
		<SPELL type="sorcery" name="Tiger Dines on Bark"/>
		<SPELLABILITY/>
		<KARMA spend="Perception-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Clay Skin"/>
		<OPTIONALTALENT name="Enhanced Matrix" limitation="S1"/>
		<OPTIONALTALENT name="Enhanced Matrix" limitation="S2"/>
		<OPTIONALTALENT name="Hypnotize"/>
		<OPTIONALTALENT name="Orbiting Spy"/>
		<OPTIONALTALENT name="Steel Thought"/>
		<OPTIONALTALENT name="Temper Self"/>
		<OPTIONALTALENT name="Willforce"/>
		<DISCIPLINETALENT name="Resist Taunt"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Awaken"/>
		<SPELL type="sorcery" name="Counterspell"/>
		<SPELL type="sorcery" name="Flying Carpet"/>
		<SPELL type="sorcery" name="Giant Size"/>
		<SPELL type="sorcery" name="Giu Shapes the Clay"/>
		<SPELL type="sorcery" name="Heat Metal Armor"/>
		<SPELL type="sorcery" name="Ironwood"/>
		<SPELL type="sorcery" name="Mage Armor"/>
		<SPELL type="sorcery" name="Makeshift Missile"/>
		<SPELL type="sorcery" name="Passion’s Eyes See Below"/>
		<SPELL type="sorcery" name="Shattering Stone"/>
		<SPELL type="sorcery" name="Wither Limb"/>
		<SPELLABILITY/>
		<ABILITY>Fluid Reality</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Graceful Exit"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Giant Takes One Step"/>
		<SPELL type="sorcery" name="Mai-Lo Becomes a Teacup"/>
		<SPELL type="sorcery" name="Makeshift Weapon"/>
		<SPELL type="sorcery" name="Princess Dreams of Serpents"/>
		<SPELL type="sorcery" name="Sleep"/>
		<SPELL type="sorcery" name="Spellstore"/>
		<KARMA spend="Willpower-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Steely Stare"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Beastform"/>
		<SPELL type="sorcery" name="Bone Pudding"/>
		<SPELL type="sorcery" name="Cloud Summon"/>
		<SPELL type="sorcery" name="Cold Storage"/>
		<SPELL type="sorcery" name="Infant Takes First Step"/>
		<SPELL type="sorcery" name="Reverse Withering"/>
		<SPELL type="sorcery" name="Teacup Becomes Dagger"/>
		<SPELL type="sorcery" name="Walk Through"/>
		<KARMA spend="spell effect tests"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="True Sight"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Giu Makes Many Pots"/>
		<SPELL type="sorcery" name="Massive Missiles"/>
		<SPELL type="sorcery" name="Prince Wears New Face"/>
		<SPELL type="sorcery" name="Princess Trapped in Mirror"/>
		<SPELL type="sorcery" name="Silence Metal"/>
		<SPELL type="sorcery" name="Teacup Finds New Friends"/>
		<SPELL type="sorcery" name="Waterspout"/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Armored Matrix" limitation="S1"/>
		<OPTIONALTALENT name="Armored Matrix" limitation="S2"/>
		<OPTIONALTALENT name="Armored Matrix" limitation="S3"/>
		<OPTIONALTALENT name="Champion Challenge"/>
		<OPTIONALTALENT name="Hold Thread"/>
		<OPTIONALTALENT name="Mind Wave"/>
		<OPTIONALTALENT name="Temper Other"/>
		<OPTIONALTALENT name="Wound Transfer"/>
		<DISCIPLINETALENT name="Astral Pocket"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Caterpillar Spins Cocoon"/>
		<SPELL type="sorcery" name="Cloud Banish"/>
		<SPELL type="sorcery" name="Giant Stomps His Feet"/>
		<SPELL type="sorcery" name="Reattach Limb"/>
		<SPELL type="sorcery" name="Spider Spins Its Web"/>
		<SPELL type="sorcery" name="Thundering Walls"/>
		<KARMA spend="Recovery Tests"/>
		<ABILITY>Immaculate Imagination</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Animate Object"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Earth and Air"/>
		<SPELL type="sorcery" name="Fire and Water"/>
		<SPELL type="sorcery" name="Petrify"/>
		<SPELL type="sorcery" name="Warp Astral Space"/>
		<SPELL type="sorcery" name="Warrior Raises His Shield"/>
		<DEFENSE kind="spell"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Reshape Object"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Alter Life"/>
		<SPELL type="sorcery" name="Mao Tends the Herd"/>
		<SPELL type="sorcery" name="Sculptor Chisels the Stone"/>
		<SPELL type="sorcery" name="Shatter Pattern"/>
		<SPELL type="sorcery" name="Wood Blade"/>
		<DEFENSE kind="social"/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Casting Pattern"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Alter Form"/>		
		<DEFENSE kind="spell"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Moving Earth"/>
		<OPTIONALTALENT name="Multi-Weaving"/>
		<OPTIONALTALENT name="Shared Matrix" limitation="S1"/>
		<OPTIONALTALENT name="Shared Matrix" limitation="S2"/>
		<OPTIONALTALENT name="Shared Matrix" limitation="S3"/>
		<OPTIONALTALENT name="Soul Shatter"/>
		<DISCIPLINETALENT name="Spell Crystal Lock"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Restore Pattern"/>
		<DEFENSE kind="social"/>
		<KARMASTEP/>
		<ABILITY>Reinvention</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Astral Web"/>
		<TALENTABILITY/>
		<SPELL type="sorcery" name="Lao Curses the Emperor"/>
		<DEFENSE kind="spell"/>
		<INITIATIVE/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Effect Pattern"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<DEFENSE kind="physical"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>recognize types magic use, identify specific uses Sorcery; knowledge: magical rituals;(CPG p.67)</HALFMAGIC>
</DISCIPLINE>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED4de/Schütze.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Schütze" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="5" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Aufmerksamkeit"/>
		<OPTIONALTALENT name="Beeindrucken"/>
		<OPTIONALTALENT name="Erster Eindruck"/>
		<OPTIONALTALENT name="Heimlicher Schritt"/>
		<OPTIONALTALENT name="Klettern"/>
		<OPTIONALTALENT name="Navigation"/>
		<OPTIONALTALENT name="Spurenlesen"/>
		<OPTIONALTALENT name="Tieranalyse"/>
		<OPTIONALTALENT name="Wildnisüberleben"/>
		<OPTIONALTALENT name="Wurfwaffen"/>
		<FREETALENT name="Projektil Rufen"/>
		<DISCIPLINETALENT name="Fadenweben" limitation="Pfeil Weben"/>
		<DISCIPLINETALENT name="Blattschuss"/>
		<DISCIPLINETALENT name="Hieb Ausweichen"/>
		<DISCIPLINETALENT name="Magische Markierung"/>
		<DISCIPLINETALENT name="Projektilwaffen"/>
		<TALENTABILITY/>
		<KARMA spend="Für Wahrnehmungsproben auf Sicht basierend"/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Mystische Verfolgung"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Kampfsinn"/>
		<TALENTABILITY/>
		<KARMA spend="Für Initiativproben"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Weitschuss"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Ablenken"/>
		<OPTIONALTALENT name="Bannmarkierung"/>
		<OPTIONALTALENT name="Beweisanalyse"/>
		<OPTIONALTALENT name="Eiserner Wille"/>
		<OPTIONALTALENT name="Etikette"/>
		<OPTIONALTALENT name="Fremdsprachen"/>
		<OPTIONALTALENT name="Gefahrensinn"/>
		<OPTIONALTALENT name="Konversation"/>
		<OPTIONALTALENT name="Starrsinn"/>
		<OPTIONALTALENT name="Tigersprung"/>
		<DISCIPLINETALENT name="Schwachstelle Erkennen"/>
		<TALENTABILITY/>
		<KARMA spend="Für Schadensproben mit Fernkampfwaffen"/>
		<ABILITY>Projektil Erschaffen</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Gezielter Querschläger"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Brandpfeil"/>
		<TALENTABILITY/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Zweiter Schuss"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<KARMARITUAL>Bitte füge eine Kurzbeschreibung für ein Karmaritual ein, die Dauer beträgt 30 Min.</KARMARITUAL>
	<HALFMAGIC>Pflege von Fernkampfwaffen; Erkennen aller Arten von  Fernkampfwaffen, Munition oder Hersteller</HALFMAGIC>
</DISCIPLINE>

=== lortas/Earthdawn-Character-Editor/config/disciplines/Troubadour.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<DISCIPLINE  name="Troubadour" lang="en" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../earthdawndiscipline.xsd">
	<DURABILITY circle="1" death="6" unconsciousness="5"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Emotion Song"/>
		<OPTIONALTALENT name="Haggle"/>
		<OPTIONALTALENT name="Melee Weapons"/>
		<OPTIONALTALENT name="Read/Write Language"/>
		<OPTIONALTALENT name="Speak Language"/>
		<DISCIPLINETALENT name="First Impression"/>
		<DISCIPLINETALENT name="Impress"/>
		<DISCIPLINETALENT name="Item History"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Mimic Voice"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Etiquette"/>
		<OPTIONALTALENT name="Heartening Laugh"/>
		<OPTIONALTALENT name="Last Impression"/>
		<OPTIONALTALENT name="Taunt"/>
		<OPTIONALTALENT name="Throwing Weapons"/>
		<OPTIONALTALENT name="Winning Smile"/>
		<DISCIPLINETALENT name="Disguise Self"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Empathic Sense"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Story Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Charisma-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Blade Juggle"/>
		<OPTIONALTALENT name="Book Memory"/>
		<OPTIONALTALENT name="Diplomacy"/>
		<OPTIONALTALENT name="Engaging Banter"/>
		<OPTIONALTALENT name="Graceful Exit"/>
		<OPTIONALTALENT name="Performance"/>
		<OPTIONALTALENT name="Research"/>
		<OPTIONALTALENT name="Slough Blame"/>
		<DISCIPLINETALENT name="Inspire Others"/>
		<TALENTABILITY/>
		<ABILITY>One Last Word</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Resist Taunt"/>
		<TALENTABILITY/>
		<KARMA spend="Perception-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Leadership"/>
		<TALENTABILITY/>
		<KARMA spend="another's person social Action Test"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Lion Heart"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
</DISCIPLINE>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED4en/Thief.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Thief" lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="5" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Climbing"/>
		<OPTIONALTALENT name="First Impression"/>
		<OPTIONALTALENT name="Great Leap"/>
		<OPTIONALTALENT name="Melee Weapons"/>
		<OPTIONALTALENT name="Missile Weapons"/>
		<OPTIONALTALENT name="Sprint"/>
		<OPTIONALTALENT name="Surprise Strike"/>
		<OPTIONALTALENT name="Taunt"/>
		<OPTIONALTALENT name="Throwing Weapons"/>
		<FREETALENT name="Danger Sense"/>
		<DISCIPLINETALENT name="Awareness"/>
		<DISCIPLINETALENT name="Thread Weaving" limitation="Thief Weaving"/>
		<DISCIPLINETALENT name="Lock Picking"/>
		<DISCIPLINETALENT name="Picking Pockets"/>
		<DISCIPLINETALENT name="Stealthy Stride"/>
		<TALENTABILITY/>
		<KARMA spend="on any Charisma-based test when the adept is attempting to deceive a target"/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Disarm Trap"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Haggle"/>
		<TALENTABILITY/>
		<KARMA spend="on Initiative tests"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Conceal Object"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Blade Juggle"/>
		<OPTIONALTALENT name="Call Missile"/>
		<OPTIONALTALENT name="Dead Fall"/>
		<OPTIONALTALENT name="Mystic Pursuit"/>
		<OPTIONALTALENT name="Disguise Self"/>
		<OPTIONALTALENT name="Graceful Exit"/>
		<OPTIONALTALENT name="Mimic Voice"/>
		<OPTIONALTALENT name="Second Weapon"/>
		<OPTIONALTALENT name="Spot Armor Flaw"/>
		<OPTIONALTALENT name="True Sight"/>
		<DISCIPLINETALENT name="Engaging Banter"/>
		<TALENTABILITY/>
		<KARMA spend="on Attack tests against a Surprised/Blindsided opponent"/>
		<ABILITY>Shadowcloak</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Slough Blame"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Fast Hand"/>
		<TALENTABILITY/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="False Sight"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>Build or bypass security measures and recognize types of locking mechanisms</HALFMAGIC>
</DISCIPLINE>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED3en/Wizard.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Wizard" lang="en" bookref="PG p.56" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="4" unconsciousness="3"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Arcane Mutterings"/>
		<OPTIONALTALENT name="Conversation"/>
		<OPTIONALTALENT name="Creature Analysis"/>
		<OPTIONALTALENT name="Evidence Analysis"/>
		<OPTIONALTALENT name="Spell Matrix" limitation="W2"/>
		<DISCIPLINETALENT name="Astral Sight"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Read/Write Magic"/>
		<DISCIPLINETALENT name="Spellcasting"/>
		<DISCIPLINETALENT name="Spell Matrix" limitation="W1"/>
		<DISCIPLINETALENT name="Thread Weaving" limitation="Wizardry"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Astral Sense"/>
		<SPELL type="wizard" name="Bedazzling Display of Logical Analysis"/>
		<SPELL type="wizard" name="Crushing Will"/>
		<SPELL type="wizard" name="Dispel Magic"/>
		<SPELL type="wizard" name="Divine Aura"/>
		<SPELL type="wizard" name="Flame Flash"/>
		<SPELL type="wizard" name="Ignite"/>
		<SPELL type="wizard" name="Iron Hand"/>
		<SPELL type="wizard" name="Mind Dagger"/>
		<SPELL type="wizard" name="Silent Converse"/>
		<SPELL type="wizard" name="Triangulate"/>
		<SPELL type="wizard" name="Wall Walker"/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Abate Curse"/>
		<OPTIONALTALENT name="Detect Weapon"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Item History"/>
		<OPTIONALTALENT name="Search"/>
		<OPTIONALTALENT name="Speak Language"/>
		<OPTIONALTALENT name="Spell Matrix" limitation="W3"/>
		<OPTIONALTALENT name="Spell Matrix" limitation="W4"/>
		<DISCIPLINETALENT name="Read/Write Language"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="And His Money"/>
		<SPELL type="wizard" name="Astral Shield"/>
		<SPELL type="wizard" name="Clean"/>
		<SPELL type="wizard" name="Dodge Boost"/>
		<SPELL type="wizard" name="Rope Ladder"/>
		<SPELL type="wizard" name="Seal"/>
		<SPELL type="wizard" name="Vines"/>
		<SPELL type="wizard" name="Wake-Up Call"/>
		<SPELLABILITY/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Book Memory"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Aura Strike"/>
		<SPELL type="wizard" name="Catwalk"/>
		<SPELL type="wizard" name="Combat Fury"/>
		<SPELL type="wizard" name="False Aura"/>
		<SPELL type="wizard" name="Healing Sleep"/>
		<SPELL type="wizard" name="Identify Spell"/>
		<SPELL type="wizard" name="Leaps and Bounds"/>
		<SPELL type="wizard" name="Levitate"/>
		<SPELL type="wizard" name="Notice Not"/>
		<SPELL type="wizard" name="Ork Stoke"/>
		<SPELL type="wizard" name="Quicken Pace"/>
		<SPELL type="wizard" name="Seeking Sight"/>
		<SPELL type="wizard" name="Shatter Lock"/>
		<SPELL type="wizard" name="Water Wings"/>
		<SPELL type="wizard" name="Wizard Mark"/>
		<SPELLABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Research"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Ball of String"/>
		<SPELL type="wizard" name="Binding Threads"/>
		<SPELL type="wizard" name="Buoyancy"/>
		<SPELL type="wizard" name="Dust Devil"/>
		<SPELL type="wizard" name="Hair Frenzy"/>
		<SPELL type="wizard" name="Icy Protection"/>
		<SPELL type="wizard" name="Identify Magic"/>
		<SPELL type="wizard" name="Inventory"/>
		<SPELL type="wizard" name="Juggler's Touch"/>
		<SPELL type="wizard" name="Kaer Knocking"/>
		<SPELL type="wizard" name="Karmic Connection"/>
		<SPELL type="wizard" name="Relax"/>
		<SPELL type="wizard" name="Repair Lock"/>
		<SPELL type="wizard" name="Thorny Retreat"/>
		<SPELL type="wizard" name="Trust"/>
		<SPELL type="wizard" name="Wizard's Cloak"/>
		<SPELLABILITY/>
		<KARMA spend="Perception-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Detect Trap"/>
		<OPTIONALTALENT name="Direction Sense"/>
		<OPTIONALTALENT name="Enhanced Matrix" limitation="W1"/>
		<OPTIONALTALENT name="Enhanced Matrix" limitation="W2"/>
		<OPTIONALTALENT name="Lifesight"/>
		<OPTIONALTALENT name="Lip Reading"/>
		<OPTIONALTALENT name="Orbiting Spy"/>
		<OPTIONALTALENT name="Willforce"/>
		<DISCIPLINETALENT name="Steel Thought"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Counterspell"/>
		<SPELL type="wizard" name="Giant Size"/>
		<SPELL type="wizard" name="Heat Metal Armor"/>
		<SPELL type="wizard" name="Invigorate"/>
		<SPELL type="wizard" name="Kaer Pictographs"/>
		<SPELL type="wizard" name="Mage Armor"/>
		<SPELL type="wizard" name="Makeshift Missile"/>
		<SPELL type="wizard" name="Mystic Shock"/>
		<SPELL type="wizard" name="Sanctuary"/>
		<SPELL type="wizard" name="Slow"/>
		<SPELL type="wizard" name="Solo Flight"/>
		<SPELL type="wizard" name="Study Thread"/>
		<SPELLABILITY/>
		<ABILITY>Book Mage</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Book Recall"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Blood Lost"/>
		<SPELL type="wizard" name="Displace Self"/>
		<SPELL type="wizard" name="Doom Missile"/>
		<SPELL type="wizard" name="Karma Cancel"/>
		<SPELL type="wizard" name="Loan Spell"/>
		<SPELL type="wizard" name="Makeshift Weapon"/>
		<SPELL type="wizard" name="Mental Library"/>
		<SPELL type="wizard" name="Multi-Mind Dagger"/>
		<SPELL type="wizard" name="Rampage"/>
		<SPELL type="wizard" name="Razor Orb"/>
		<SPELL type="wizard" name="Sleep"/>
		<SPELL type="wizard" name="Spellstore"/>
		<KARMA spend="Willpower-Only Tests"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Resist Taunt"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Astral Gift"/>
		<SPELL type="wizard" name="Blood Boil"/>
		<SPELL type="wizard" name="Call"/>
		<SPELL type="wizard" name="Confusing Weave"/>
		<SPELL type="wizard" name="Dislodge Spell"/>
		<SPELL type="wizard" name="Lightning Cloud"/>
		<SPELL type="wizard" name="Liquid Eyes"/>
		<SPELL type="wizard" name="Move on Through"/>
		<SPELL type="wizard" name="Mystic Net"/>
		<SPELL type="wizard" name="Spell Cage"/>
		<KARMA spend="spell effect tests"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Hold Thread"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Catch Spell"/>
		<SPELL type="wizard" name="Compression Bubble"/>
		<SPELL type="wizard" name="Delay Blow"/>
		<SPELL type="wizard" name="Peacebond"/>
		<SPELL type="wizard" name="Safe Opening"/>
		<SPELL type="wizard" name="Spell Snatcher"/>
		<SPELL type="wizard" name="Wound Mask"/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
		<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Armored Matrix" limitation="W1"/>
		<OPTIONALTALENT name="Armored Matrix" limitation="W2"/>
		<OPTIONALTALENT name="Armored Matrix" limitation="W3"/>
		<OPTIONALTALENT name="Astral Pocket"/>
		<OPTIONALTALENT name="Matrix Strike"/>
		<OPTIONALTALENT name="Power Mask"/>
		<OPTIONALTALENT name="Safe Thought"/>
		<OPTIONALTALENT name="Spirit Strike"/>
		<DISCIPLINETALENT name="Range Pattern"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Matrix Split</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="True Sight"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<KARMA spend="Charisma-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Casting Pattern"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Wound Transfer"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Detect Falsehood"/>
		<OPTIONALTALENT name="First Ring of Perfection"/>
		<OPTIONALTALENT name="Multi-Tongue"/>
		<OPTIONALTALENT name="Shared Matrix" limitation="W1"/>
		<OPTIONALTALENT name="Shared Matrix" limitation="W2"/>
		<OPTIONALTALENT name="Shared Matrix" limitation="W3"/>
		<DISCIPLINETALENT name="Effect Pattern"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<KARMASTEP/>
		<ABILITY>Casting Triangle</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Detect Influence"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<INITIATIVE count="2"/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Astral Web"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<DEFENSE kind="physical"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>recognize types of magic use, identify specific uses of Wizardry; knowledge: of magical rituals (PG p.56)</HALFMAGIC>
</DISCIPLINE>
