=== lortas/Earthdawn-Character-Editor/config/earthdawndiscipline.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/discipline" xmlns="http://earthdawn.com/discipline" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="DISCIPLINEDURABILITY_type">
		<xs:attribute name="value" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="death" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="unconsciousness" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="circle" type="edt:unsigned_int" default="0"/>
	</xs:complexType>
	<xs:complexType name="DISCIPLINESPELL_type">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="edt:spellkind_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="FOREIGNTALENTS_type">
		<xs:attribute name="maxcircle" type="edt:circle_type" default="1"/>
		<xs:attribute name="mincircle" type="edt:circle_type" default="1"/>
	</xs:complexType>
	<xs:complexType name="DISCIPLINECIRCLE_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element minOccurs="0" maxOccurs="1" name="FOREIGNTALENTS" type="FOREIGNTALENTS_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="OPTIONALTALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="FREETALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="8" name="DISCIPLINETALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="1" maxOccurs="1" name="TALENTABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELL" type="DISCIPLINESPELL_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELLABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="DEFENSE" type="edt:DEFENSEABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="INITIATIVE" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTEST" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMA" type="edt:KARMAABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMASTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ABILITY" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="DISCIPLINE">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element minOccurs="1" maxOccurs="1" name="DURABILITY" type="DISCIPLINEDURABILITY_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="EASYSKILL" type="xs:string"/>
				<xs:element minOccurs="8" maxOccurs="15" name="CIRCLE" type="DISCIPLINECIRCLE_type"/>
				<xs:element minOccurs="0" maxOccurs="1" name="KARMARITUAL" type="xs:string"/>
				<xs:element minOccurs="0" maxOccurs="1" name="HALFMAGIC" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="bookref" type="xs:string" default=""/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED3"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED3en/Liberator.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Liberator" lang="en" bookref="NG p.159" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="8" unconsciousness="6"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Acrobatic Strike"/>
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Disguise Self"/>
		<OPTIONALTALENT name="Silent Walk"/>
		<OPTIONALTALENT name="Unarmed Combat"/>
		<DISCIPLINETALENT name="Freedom Search"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Lock Picking"/>
		<DISCIPLINETALENT name="Melee Weapons"/>
		<DISCIPLINETALENT name="Shackle Shrug"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Conceal Object"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Fireblood"/>
		<OPTIONALTALENT name="Heart of Freedom"/>
		<OPTIONALTALENT name="Heartening Laugh"/>
		<OPTIONALTALENT name="Surprise Strike"/>
		<OPTIONALTALENT name="Throwing Weapons"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<DISCIPLINETALENT name="Free Mind"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Shout of Jusice"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Freedom Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Charisma-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Dead Fall"/>
		<OPTIONALTALENT name="Disarm"/>
		<OPTIONALTALENT name="Heal Slave"/>
		<OPTIONALTALENT name="Leadership"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Resist Taunt"/>
		<OPTIONALTALENT name="Second Attack"/>
		<OPTIONALTALENT name="Temper Self"/>
		<DISCIPLINETALENT name="False Shackles"/>
		<TALENTABILITY/>
		<ABILITY>Shield of the Weak</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Hoard Blows"/>
		<TALENTABILITY/>
		<KARMA spend="Willpower-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Mind Blade"/>
		<TALENTABILITY/>
		<KARMA spend="Action Test made against a slaver or made to resist a slaver´s abilities"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Power Mask"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Champion Challenge"/>
		<OPTIONALTALENT name="Critical Hit"/>
		<OPTIONALTALENT name="Frenzy"/>
		<OPTIONALTALENT name="Life Check"/>
		<OPTIONALTALENT name="Pin"/>
		<OPTIONALTALENT name="Resist Pain"/>
		<OPTIONALTALENT name="Steel Thought"/>
		<OPTIONALTALENT name="Temper Other"/>
		<DISCIPLINETALENT name="Prison Call"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Freedom Quest</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Mind Armor"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Escape Divination"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Impossible Hide"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Blood Guilt Weapon"/>
		<OPTIONALTALENT name="Chameleon"/>
		<OPTIONALTALENT name="Echo Location"/>
		<OPTIONALTALENT name="Ethereal Weapon"/>
		<OPTIONALTALENT name="Multi-Strike"/>
		<OPTIONALTALENT name="Rushing Attack"/>
		<DISCIPLINETALENT name="Second Chance"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<KARMASTEP/>
		<ABILITY>Heart of Rebellion</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Vitality"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Vital Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>gathering intelligence to inspire rebellion; knowledge: slaver tactics/ strategy, events of the Great Uprising and Hrak Gron’s life;(NG p.159)</HALFMAGIC>
</DISCIPLINE>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED3en/Purifier.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE  name="Purifier" lang="en" bookref="NG p.172" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="7" unconsciousness="6"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Acrobatic Strike"/>
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Battle Shout"/>
		<OPTIONALTALENT name="Sprint"/>
		<OPTIONALTALENT name="Wilderness Survival"/>
		<DISCIPLINETALENT name="Body Control"/>
		<DISCIPLINETALENT name="Clay Skin"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Unarmed Combat"/>
		<DISCIPLINETALENT name="Wound Balance"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Creature Analysis"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Heartening Laugh"/>
		<OPTIONALTALENT name="Maneuver"/>
		<OPTIONALTALENT name="Swift Kick"/>
		<OPTIONALTALENT name="Throwing Weapons"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<OPTIONALTALENT name="Tracking"/>
		<DISCIPLINETALENT name="Lifesight"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Spirit Talk"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Earth Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Strengh-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Astral Sight"/>
		<OPTIONALTALENT name="Earth Skin"/>
		<OPTIONALTALENT name="Great Leap"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Resist Taunt"/>
		<OPTIONALTALENT name="Steel Thought"/>
		<OPTIONALTALENT name="Steely Stare"/>
		<OPTIONALTALENT name="Temper Self"/>
		<DISCIPLINETALENT name="Earth Bond"/>
		<TALENTABILITY/>
		<ABILITY>Cleanse</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Life Check"/>
		<TALENTABILITY/>
		<KARMA spend="Toughness-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Crushing Blow"/>
		<TALENTABILITY/>
		<KARMA spend="unarmend Damage Tests"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Momentum Attack"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Critical Hit"/>
		<OPTIONALTALENT name="Frenzy"/>
		<OPTIONALTALENT name="Lion Spirit"/>
		<OPTIONALTALENT name="Matrix Strike"/>
		<OPTIONALTALENT name="Metal Ward"/>
		<OPTIONALTALENT name="Poison Resistance"/>
		<OPTIONALTALENT name="Resist Pain"/>
		<OPTIONALTALENT name="Spirit Strike"/>
		<DISCIPLINETALENT name="Safe Path"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Earth's Avenger</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Plant Shelter"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Vitality"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<DEFENSE kind="social"/>
		<KARMA spend="Willpower-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Earth Armor"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Chameleon"/>
		<OPTIONALTALENT name="Detect Influence"/>
		<OPTIONALTALENT name="Moving Earth"/>
		<OPTIONALTALENT name="Rushing Attack"/>
		<OPTIONALTALENT name="Stone Skin"/>
		<OPTIONALTALENT name="Whirlwind"/>
		<DISCIPLINETALENT name="Second Chance"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<KARMASTEP/>
		<ABILITY>Sanctify</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Vital Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Elemental Walk"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>knowledge: all aspects of nature, preserving natural environs, all that tends to currupt nature (including Horrors, misdeeds of Namegiver civilization); Skill: Navigation, Wilderness Survival;(NG p.175)</HALFMAGIC>
</DISCIPLINE>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED4de/Krieger.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Krieger" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="7" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Ablenken"/>
		<OPTIONALTALENT name="Akrobatische Verteidigung"/>
		<OPTIONALTALENT name="Feuerblut"/>
		<OPTIONALTALENT name="Gefahrensinn"/>
		<OPTIONALTALENT name="Kampfsinn"/>
		<OPTIONALTALENT name="Manövrieren"/>
		<OPTIONALTALENT name="Projektilwaffen"/>
		<OPTIONALTALENT name="Schildschlag"/>
		<OPTIONALTALENT name="Taktik"/>
		<OPTIONALTALENT name="Waffenloser Kampf"/>
		<DISCIPLINETALENT name="Fadenweben" limitation="Kriegsweben"/>
		<DISCIPLINETALENT name="Hieb Ausweichen"/>
		<DISCIPLINETALENT name="Holzhaut"/>
		<DISCIPLINETALENT name="Nahkampfwaffen"/>
		<DISCIPLINETALENT name="Tigersprung"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Standhaftigkeit"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Lufttanz"/>
		<TALENTABILITY/>
		<KARMA spend="Erholungsproben"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Wasserfallschlag"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Entwaffnen"/>
		<OPTIONALTALENT name="Etikette"/>
		<OPTIONALTALENT name="Führung"/>
		<OPTIONALTALENT name="Letzte Rettung"/>
		<OPTIONALTALENT name="Löwenherz"/>
		<OPTIONALTALENT name="Nachtreten"/>
		<OPTIONALTALENT name="Schwachstelle Erkennen"/>
		<OPTIONALTALENT name="Schwungvoller Angriff"/>
		<OPTIONALTALENT name="Stählerner Blick"/>
		<OPTIONALTALENT name="Zweitwaffe"/>
		<DISCIPLINETALENT name="Erdhaut"/>
		<TALENTABILITY/>
		<KARMA spend="auf beliebige Schadensproben im Nahkampf"/>
		<ABILITY>Kampfriten</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Ätherhaut"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Hammerschlag"/>
		<TALENTABILITY/>
		<RECOVERYTESTPERDAY/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Zweiter Angriff"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<KARMARITUAL>Bitte füge eine Kurzbeschreibung für ein Karmaritual ein, die Dauer beträgt 30 Min. </KARMARITUAL>
	<HALFMAGIC>Pflege und Reparatur von  Waffen und Rüstung; Wissen über: Militär Strategien und Taktik, Ereignisse in Barsaive's Militär Geschichte, Wahrnehmung von: Kriegerorden, berühmte Krieger der Vergangenheit, altertümliche Waffen und Rüstungen</HALFMAGIC>
</DISCIPLINE>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED3en/Winddancer.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Winddancer" lang="en" bookref="NG p.201" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="6" unconsciousness="5"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Air Speaking"/>
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Impress"/>
		<OPTIONALTALENT name="Melee Weapons"/>
		<OPTIONALTALENT name="Speak Language"/>
		<DISCIPLINETALENT name="Conversation"/>
		<DISCIPLINETALENT name="Etiquette"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Taunt"/>
		<DISCIPLINETALENT name="Wind Dance"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Distract"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Emotion Song"/>
		<OPTIONALTALENT name="Empathic Sense"/>
		<OPTIONALTALENT name="Engaging Banter"/>
		<OPTIONALTALENT name="Haggle"/>
		<OPTIONALTALENT name="Heartening Laugh"/>
		<OPTIONALTALENT name="Mimic Voice"/>
		<DISCIPLINETALENT name="Diplomacy"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Bird Song"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Dance Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Charisma-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Arcane Mutterings"/>
		<OPTIONALTALENT name="Dead Fall"/>
		<OPTIONALTALENT name="Enduring Art"/>
		<OPTIONALTALENT name="Fast Hand"/>
		<OPTIONALTALENT name="Inspire Others"/>
		<OPTIONALTALENT name="Item History"/>
		<OPTIONALTALENT name="Lasting Impression"/>
		<OPTIONALTALENT name="Lip Reading"/>
		<DISCIPLINETALENT name="Resist Taunt"/>
		<TALENTABILITY/>
		<ABILITY>Judgment Call</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Graceful Exit"/>
		<TALENTABILITY/>
		<KARMA spend="Perception-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Leadership"/>
		<TALENTABILITY/>
		<KARMA spend="Interaction Test"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Hypnotize"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Incite Mob"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Mind Wave"/>
		<OPTIONALTALENT name="Rally"/>
		<OPTIONALTALENT name="Safe Thought"/>
		<OPTIONALTALENT name="Song of Deflection"/>
		<OPTIONALTALENT name="Mind Wave"/>
		<OPTIONALTALENT name="Thought Link"/>
		<OPTIONALTALENT name="True Sight"/>
		<DISCIPLINETALENT name="Slough Blame"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Captivate</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Bardic Voice"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<KARMA spend="Dexterity-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Detect Falsehood"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<DEFENSE kind="physical"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Truth Skit"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Animate Object"/>
		<OPTIONALTALENT name="Blood Guilt Weapon"/>
		<OPTIONALTALENT name="Champion Challenge"/>
		<OPTIONALTALENT name="Detect Influence"/>
		<OPTIONALTALENT name="Echo Location"/>
		<OPTIONALTALENT name="First Ring of Perfection"/>
		<DISCIPLINETALENT name="Multi-Tongue"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<KARMASTEP/>
		<ABILITY>Wing Mastery</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Second Chance"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Aura Armor"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>whenever perform for audiences; knowledge: legends, myths, rites, traditions, folklore of windling culture/ cultures studied personally; (NG p.203)</HALFMAGIC>
</DISCIPLINE>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED4de/Geisterbeschwörer.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Geisterbeschwörer" lang="de"  rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="3" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Arkanes Gefasel"/>
		<OPTIONALTALENT name="Aufmerksamkeit"/>
		<OPTIONALTALENT name="Fluch Unterdrücken"/>
		<OPTIONALTALENT name="Fremdsprachen"/>
		<OPTIONALTALENT name="Heimlicher Schritt"/>
		<OPTIONALTALENT name="Hieb Ausweichen"/>
		<OPTIONALTALENT name="Lesen/Schreiben"/>
		<OPTIONALTALENT name="Magie Neutralisieren"/>
		<OPTIONALTALENT name="Nachtflieger Befehligen"/>
		<OPTIONALTALENT name="Standardmatrix" limitation="G1"/>
		<FREETALENT name="Standardmatrix" limitation="F1"/>
		<FREETALENT name="Standardmatrix" limitation="F2"/>
		<DISCIPLINETALENT name="Astralsicht"/>
		<DISCIPLINETALENT name="Spruchzauberei"/>
		<DISCIPLINETALENT name="Struktur Verstehen"/>
		<DISCIPLINETALENT name="Verängstigen"/>
		<DISCIPLINETALENT name="Fadenweben" limitation="Geisterbeschwörung"/>
		<TALENTABILITY/>
		<SPELL type="nether" name="Astralspeer"/>
		<SPELL type="nether" name="Ätherische Finsternis"/>
		<SPELL type="nether" name="Augenblick des Todes"/>
		<SPELL type="nether" name="Dunkler Bote"/>
		<SPELL type="nether" name="Geisterhand"/>
		<SPELL type="nether" name="Geisterpfeil"/>
		<SPELL type="nether" name="Kleiner Bannkreis"/>
		<SPELL type="nether" name="Knochenkreis"/>
		<SPELL type="nether" name="Schattenverschmelzung"/>
		<SPELL type="nether" name="Seelenlose Augen"/>
		<SPELL type="nether" name="Seelenrüstung"/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Eiserner Wille"/>
		<TALENTABILITY/>
		<SPELL type="nether" name="Aspekt des Nebelgeistes"/>
		<SPELL type="nether" name="Kreis der Kälte"/>
		<SPELL type="nether" name="Nebelgeist Beschwören"/>
		<SPELL type="nether" name="Nebelschild"/>
		<SPELL type="nether" name="Schädel des Todes"/>
		<SPELL type="nether" name="Schattengeflüster"/>
		<SPELL type="nether" name="Schneide der Nacht"/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Geistersprache"/>
		<TALENTABILITY/>
		<SPELL type="nether" name="Aspekt des Feigen Herumschleichens"/>
		<SPELL type="nether" name="Aspekt des Knochengeistes"/>
		<SPELL type="nether" name="Grabesbotschaft"/>
		<SPELL type="nether" name="Knochengeist Beschwören"/>
		<SPELL type="nether" name="Nebel der Angst"/>
		<SPELL type="nether" name="Pfeil der Nacht"/>
		<SPELL type="nether" name="Schmerzen"/>
		<KARMA spend="beliebige Probe gegen Dämonen, Konstrukte, Untote"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Geisterbann"/>
		<TALENTABILITY/>
		<SPELL type="nether" name="Aspekt des Bedrohlichen Tyrannen"/>
		<SPELL type="nether" name="Böser Blick"/>
		<SPELL type="nether" name="Dunkler Spion"/>
		<SPELL type="nether" name="Letzte Chance"/>
		<SPELL type="nether" name="Sichtfenster"/>
		<SPELL type="nether" name="Umhang des Nachtfliegers"/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Astrale Interferenz"/>
		<OPTIONALTALENT name="Erweiterte Matrix" limitation="G2"/>
		<OPTIONALTALENT name="Forschen"/>
		<OPTIONALTALENT name="Geisterreittier"/>
		<OPTIONALTALENT name="Hartnäckiges Gewebe"/>
		<OPTIONALTALENT name="Lebensblick"/>
		<OPTIONALTALENT name="Löwenherz"/>
		<OPTIONALTALENT name="Schadensverteilung"/>
		<OPTIONALTALENT name="Stählener Blick"/>
		<OPTIONALTALENT name="Verbannen"/>
		<FREETALENT name="Erweiterte Matrix" replace="Standardmatrix" limitation="F1"/>
		<DISCIPLINETALENT name="Beschwören" limitation="Verbündete Geister"/>
		<TALENTABILITY/>
		<SPELL type="nether" name="Aspekt des Grausamen Arztes"/>
		<SPELL type="nether" name="Astraler Schutzkreis"/>
		<SPELL type="nether" name="Erblinden"/>
		<SPELL type="nether" name="Staub zu Staub"/>
		<SPELL type="nether" name="Verdorren"/>
		<SPELL type="nether" name="Verdorren Umkehren"/>
		<KARMA spend="den Malus eines Zaubers, den man wirkt, um 2 zu erhöhen"/>
		<ABILITY>Blutbeschwörung</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Willensstärke"/>
		<TALENTABILITY/>
		<SPELL type="nether" name="Astralschlund"/>
		<SPELL type="nether" name="Durch den Schatten Treten"/>
		<SPELL type="nether" name="Erholung"/>
		<SPELL type="nether" name="Freundliche Finsternis"/>
		<SPELL type="nether" name="Knochenbrecher"/>
		<SPELL type="nether" name="Schwächende Düsternis"/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Kreisender Spion"/>
		<TALENTABILITY/>
		<SPELL type="nether" name="Aspekt des Gelegenheitsmörders"/>
		<SPELL type="nether" name="Astrales Leuchtfeuer"/>
		<SPELL type="nether" name="Herzbeklemmung"/>
		<SPELL type="nether" name="Knochenpudding"/>
		<SPELL type="nether" name="Lähmkreis"/>
		<SPELL type="nether" name="Üble Dämpfe"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Faden Halten"/>
		<TALENTABILITY/>
		<SPELL type="nether" name="Aspekt des Astralen Gelehrten"/>
		<SPELL type="nether" name="Astralklinge"/>
		<SPELL type="nether" name="Dahinsiechen"/>
		<SPELL type="nether" name="Dämonenruf"/>
		<SPELL type="nether" name="Geisterportal"/>
		<SPELL type="nether" name="Schattenfessel"/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<KARMARITUAL>Bitte füge eine Kurzbeschreibung für ein Karmaritual ein, die Dauer beträgt 30 Min. </KARMARITUAL>
	<HALFMAGIC>Wissen: Erkenne Geisterbeschwörer Magie und Untoten/Geister, Verstehe Blutmagie Rituale und die Wirkung von Blutamuletten; Wahrnehmungsprobe: Präsenz von Geistern spüren</HALFMAGIC>
</DISCIPLINE>
