=== lortas/Earthdawn-Character-Editor/config/earthdawndiscipline.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/discipline" xmlns="http://earthdawn.com/discipline" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="DISCIPLINEDURABILITY_type">
		<xs:attribute name="value" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="death" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="unconsciousness" type="edt:unsigned_int" default="0"/>
		<xs:attribute name="circle" type="edt:unsigned_int" default="0"/>
	</xs:complexType>
	<xs:complexType name="DISCIPLINESPELL_type">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="edt:spellkind_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="FOREIGNTALENTS_type">
		<xs:attribute name="maxcircle" type="edt:circle_type" default="1"/>
		<xs:attribute name="mincircle" type="edt:circle_type" default="1"/>
	</xs:complexType>
	<xs:complexType name="DISCIPLINECIRCLE_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element minOccurs="0" maxOccurs="1" name="FOREIGNTALENTS" type="FOREIGNTALENTS_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="OPTIONALTALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="FREETALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="8" name="DISCIPLINETALENT" type="edt:TALENTABILITY_type"/>
			<xs:element minOccurs="1" maxOccurs="1" name="TALENTABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELL" type="DISCIPLINESPELL_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELLABILITY" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="DEFENSE" type="edt:DEFENSEABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="INITIATIVE" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="RECOVERYTEST" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMA" type="edt:KARMAABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="KARMASTEP" type="edt:DISZIPINABILITY_type"/>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="ABILITY" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="DISCIPLINE">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element minOccurs="1" maxOccurs="1" name="DURABILITY" type="DISCIPLINEDURABILITY_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="EASYSKILL" type="xs:string"/>
				<xs:element minOccurs="8" maxOccurs="15" name="CIRCLE" type="DISCIPLINECIRCLE_type"/>
				<xs:element minOccurs="0" maxOccurs="1" name="KARMARITUAL" type="xs:string"/>
				<xs:element minOccurs="0" maxOccurs="1" name="HALFMAGIC" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="bookref" type="xs:string" default=""/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED3"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED4de/Kundschafter.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Kundschafter" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="5" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Fallen Entschärfen"/>
		<OPTIONALTALENT name="Fremdsprachen"/>
		<OPTIONALTALENT name="Hieb Ausweichen"/>
		<OPTIONALTALENT name="Kampfsinn"/>
		<OPTIONALTALENT name="Lesen/Schreiben"/>
		<OPTIONALTALENT name="Nahkampfwaffen"/>
		<OPTIONALTALENT name="Projektilwaffen"/>
		<OPTIONALTALENT name="Schloss Knacken"/>
		<OPTIONALTALENT name="Tieranalyse"/>
		<OPTIONALTALENT name="Weitsprung"/>
		<FREETALENT name="Navigation"/>
		<DISCIPLINETALENT name="Fadenweben" limitation="Kundschafterweben"/>
		<DISCIPLINETALENT name="Aufmerksamkeit"/>
		<DISCIPLINETALENT name="Klettern"/>
		<DISCIPLINETALENT name="Spurenlesen"/>
		<DISCIPLINETALENT name="Wildnisüberleben"/>
		<TALENTABILITY/>
		<KARMA spend="auf Proben um etwas zu finden"/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Heimlicher Schritt"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Kompasspfeil"/>
		<TALENTABILITY/>
		<KARMA spend="auf Initiativproben"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Gefahrensinn"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Gegenstand Verbergen"/>
		<OPTIONALTALENT name="Geisterreittier"/>
		<OPTIONALTALENT name="Magische Maske"/>
		<OPTIONALTALENT name="Schwachstelle Erkennen"/>
		<OPTIONALTALENT name="Sprint"/>
		<OPTIONALTALENT name="Tierfreundschaft"/>
		<OPTIONALTALENT name="Tierische Sinne"/>
		<OPTIONALTALENT name="Tigersprung"/>
		<OPTIONALTALENT name="Überraschungsschlag"/>
		<OPTIONALTALENT name="Untrüglicher Blick"/>
		<DISCIPLINETALENT name="Beweisanalyse"/>
		<TALENTABILITY/>
		<KARMA spend="für Erholungsproben"/>
		<ABILITY>Geschärfte Sinne</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Astralsicht"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Sicherer Pfad"/>
		<TALENTABILITY/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Kreisender Spion"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<KARMARITUAL>Bitte füge eine Kurzbeschreibung für ein Karmaritual ein, die Dauer beträgt 30 Min.</KARMARITUAL>
	<HALFMAGIC>Erkennt Spuren und Fährten von Tieren und Namensgebern in der Stadt und auf dem Land; Wissen über Pflanzen, Kreaturen und Kulturen in Barsaive </HALFMAGIC>
</DISCIPLINE>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED3en/WarRider.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="War Rider" lang="en" bookref="CPG p.74" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="7" unconsciousness="6"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Animal Training"/>
		<OPTIONALTALENT name="Melee Weapons"/>
		<OPTIONALTALENT name="Throwing Weapons"/>
		<OPTIONALTALENT name="Unarmed Combat"/>
		<OPTIONALTALENT name="Wilderness Survival"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Missile Weapons"/>
		<DISCIPLINETALENT name="Surprise Strike"/>
		<DISCIPLINETALENT name="Tracking"/>
		<DISCIPLINETALENT name="Trick Riding"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Detect Weapon"/>
		<OPTIONALTALENT name="Dominate Beast"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Lasting Impression"/>
		<OPTIONALTALENT name="Long Shot"/>
		<OPTIONALTALENT name="Mystic Aim"/>
		<OPTIONALTALENT name="Wood Skin"/>
		<DISCIPLINETALENT name="Sure Mount"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Empathic Command"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Gar Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Strength-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Conceal Object"/>
		<OPTIONALTALENT name="Heal Animal"/>
		<OPTIONALTALENT name="Momentum Attack"/>
		<OPTIONALTALENT name="Mount Durability"/>
		<OPTIONALTALENT name="Steely Stare"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<OPTIONALTALENT name="True Shot"/>
		<OPTIONALTALENT name="Wheeling Attack"/>
		<DISCIPLINETALENT name="Lion Heart"/>
		<TALENTABILITY/>
		<ABILITY>Life in Stirrups</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Wheeling Defense"/>
		<TALENTABILITY/>
		<KARMA spend="Dexterity-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Feign Retreat"/>
		<TALENTABILITY/>
		<KARMA spend="Damage Tests while mounted"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Second Shot"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Call Missile"/>
		<OPTIONALTALENT name="Call Mount"/>
		<OPTIONALTALENT name="Critical Hit"/>
		<OPTIONALTALENT name="Eagle Eye"/>
		<OPTIONALTALENT name="Life Check"/>
		<OPTIONALTALENT name="Mount Attack"/>
		<OPTIONALTALENT name="Quick Shot"/>
		<OPTIONALTALENT name="Tame Mount"/>
		<DISCIPLINETALENT name="Ambush"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Out of Nowhere</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Armor Mount"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Bestial Toughness"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Unmount"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Champion Challenge"/>
		<OPTIONALTALENT name="Ethereal Weapon"/>
		<OPTIONALTALENT name="Gain Surprise"/>
		<OPTIONALTALENT name="Screaming Arrow"/>
		<OPTIONALTALENT name="Trample"/>
		<OPTIONALTALENT name="Wind Bow"/>
		<DISCIPLINETALENT name="Bestial Resilience"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<KARMASTEP/>
		<ABILITY>Law of Might</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Vital Strike"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Multi-Shot"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<DEFENSE kind="spell"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>knowledge: mounts common to homelands; taking care mounts/ mount-related gear; tame/ train mounts; Skill: Craft Weapon missile weapons, ammunition (CPG p.77)</HALFMAGIC>
</DISCIPLINE>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED4de/Magier.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Magier" lang="de" rulesetversion="ED4" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY value="3" circle="1"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Arkanes Gefasel"/>
		<OPTIONALTALENT name="Artefaktgeschichte"/>
		<OPTIONALTALENT name="Aufmerksamkeit"/>
		<OPTIONALTALENT name="Büchergedächtnis"/>
		<OPTIONALTALENT name="Etikette"/>
		<OPTIONALTALENT name="Fremdsprachen"/>
		<OPTIONALTALENT name="Konversation"/>
		<OPTIONALTALENT name="Lesen/Schreiben"/>
		<OPTIONALTALENT name="Standardmatrix"/>
		<OPTIONALTALENT name="Tieranalyse"/>
		<FREETALENT name="Standardmatrix"/>
		<FREETALENT name="Standardmatrix"/>
		<DISCIPLINETALENT name="Forschen"/>
		<DISCIPLINETALENT name="Magie Neutralisieren"/>
		<DISCIPLINETALENT name="Spruchzauberei"/>
		<DISCIPLINETALENT name="Struktur Verstehen"/>
		<DISCIPLINETALENT name="Fadenweben" limitation="Magie"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Astralsinn"/>
		<SPELL type="wizard" name="Aura Lesen"/>
		<SPELL type="wizard" name="Blendende Zurschaustellung Logischer Analyse"/>
		<SPELL type="wizard" name="Eiserne Hand"/>
		<SPELL type="wizard" name="Flammenblitz"/>
		<SPELL type="wizard" name="Katzenaugen"/>
		<SPELL type="wizard" name="Kletterhilfe"/>
		<SPELL type="wizard" name="Mentaler Dolch"/>
		<SPELL type="wizard" name="Schneller zu Fuß"/>
		<SPELL type="wizard" name="Schnelllesen"/>
		<SPELL type="wizard" name="Verzauberte Rüstung"/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<DISCIPLINETALENT name="Astralsicht"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Astralschild"/>
		<SPELL type="wizard" name="Ausweichschub"/>
		<SPELL type="wizard" name="Fadenkreuz"/>
		<SPELL type="wizard" name="Interferenzausgleich"/>
		<SPELL type="wizard" name="Strickleiter"/>
		<SPELL type="wizard" name="Vernichtender Wille"/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Hartnäckiges Gewebe"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Astralvisier"/>
		<SPELL type="wizard" name="Auraschlag"/>
		<SPELL type="wizard" name="Kampfeswut"/>
		<SPELL type="wizard" name="Levitation"/>
		<SPELL type="wizard" name="Magie Identifizieren"/>
		<SPELL type="wizard" name="Magiermal"/>
		<KARMA spend="um sich zu erinnern (einschl. Wissensproben)"/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Eisener Wille"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Berührung des Gauklers"/>
		<SPELL type="wizard" name="Fesselnde Fäden"/>
		<SPELL type="wizard" name="Gewachsenes Bewusstsein"/>
		<SPELL type="wizard" name="Last Erleichtern"/>
		<SPELL type="wizard" name="Leitfaden"/>
		<SPELL type="wizard" name="Umhang des Magiers"/>
		<DEFENSE kind="social"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Beweisanalyse"/>
		<OPTIONALTALENT name="Diplomatie"/>
		<OPTIONALTALENT name="Erweiterte Matrix"/>
		<OPTIONALTALENT name="Hieb Ausweichen"/>
		<OPTIONALTALENT name="Hypnotisieren"/>
		<OPTIONALTALENT name="Kompasspfeil"/>
		<OPTIONALTALENT name="Lebensblick"/>
		<OPTIONALTALENT name="Machtmaskierung"/>
		<OPTIONALTALENT name="Starrsinn"/>
		<OPTIONALTALENT name="Untrüglicher Blick"/>
		<FREETALENT name="Erweiterte Matrix" replace="Standardmatrix"/>
		<DISCIPLINETALENT name="Astrale Interferenz"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Fliegen"/>
		<SPELL type="wizard" name="Mystischer Schock"/>
		<SPELL type="wizard" name="Riesenwuchs"/>
		<SPELL type="wizard" name="Talent Unterbrechen"/>
		<SPELL type="wizard" name="Verlangsamen"/>
		<SPELL type="wizard" name="Waffe Herbei"/>
		<KARMA spend="um einen Selbst-Zauber auf Berührung zu ändern"/>
		<ABILITY>Buchzauberer</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Willensstärke"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Energieschild"/>
		<SPELL type="wizard" name="Intuitives Ausweichen"/>
		<SPELL type="wizard" name="Schlaf"/>
		<SPELL type="wizard" name="Verwüstung"/>
		<SPELL type="wizard" name="Zauber Verleihen"/>
		<SPELL type="wizard" name="Zerschmettern"/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Faden Halten"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Hypergeschwindigkeit"/>
		<SPELL type="wizard" name="Mystisches Netz"/>
		<SPELL type="wizard" name="Ruf"/>
		<SPELL type="wizard" name="Verknotete Fäden"/>
		<SPELL type="wizard" name="Zauber Verdrängen"/>
		<SPELL type="wizard" name="Zauberspeicher"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Fluch Unterdrücken"/>
		<TALENTABILITY/>
		<SPELL type="wizard" name="Astrale Katastrophe"/>
		<SPELL type="wizard" name="Karmablockade"/>
		<SPELL type="wizard" name="Zauber Einfangen"/>
		<SPELL type="wizard" name="Zauberdiebstahl"/>
		<SPELL type="wizard" name="Zauberkäfig"/>
		<SPELL type="wizard" name="Zerquetschen"/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<KARMARITUAL>Bitte füge eine Kurzbeschreibung für ein Karmaritual ein, die Dauer beträgt 30 Min.</KARMARITUAL>
	<HALFMAGIC>Erkennt verschiedene Arten von Magie, erkennt spezielle Anwendung von Magier-Magie; Wissen über magische Rituale </HALFMAGIC>
</DISCIPLINE>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED3en/Archer-Bowman.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Archer-Bowman" lang="en" bookref="PC p.23" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="6" unconsciousness="5"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Climbing"/>
		<OPTIONALTALENT name="Melee Weapons"/>
		<OPTIONALTALENT name="Silent Walk"/>
		<OPTIONALTALENT name="Tracking"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Missile Weapons"/>
		<DISCIPLINETALENT name="Mystic Aim"/>
		<DISCIPLINETALENT name="Throwing Weapons"/>
		<DISCIPLINETALENT name="True Shot"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Detect Weapon"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="First Impression"/>
		<OPTIONALTALENT name="Flame Arrow"/>
		<OPTIONALTALENT name="Great Leap"/>
		<OPTIONALTALENT name="Anticipate Blow"/>
		<OPTIONALTALENT name="Speak Language"/>
		<OPTIONALTALENT name="Sprint"/>
		<DISCIPLINETALENT name="Direction Arrow"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Long Shot"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Arrow Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Dexterity-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Call Missile"/>
		<OPTIONALTALENT name="Conceal Object"/>
		<OPTIONALTALENT name="Creature Analysis"/>
		<OPTIONALTALENT name="Empathic Sense"/>
		<OPTIONALTALENT name="Evidence Analysis"/>
		<OPTIONALTALENT name="Heartening Laugh"/>
		<OPTIONALTALENT name="Lip Reading"/>
		<OPTIONALTALENT name="Stopping Aim"/>
		<DISCIPLINETALENT name="Steel Thought"/>
		<TALENTABILITY/>
		<ABILITY>Arrow's Eye View</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Bank Shot"/>
		<TALENTABILITY/>
		<KARMA spend="Perception-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Impressive Shot"/>
		<TALENTABILITY/>
		<KARMA spend="ranged combat Damage Test"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Second Shot"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Blade Juggle"/>
		<OPTIONALTALENT name="Critical Hit"/>
		<OPTIONALTALENT name="Lifesight"/>
		<OPTIONALTALENT name="Rushing Attack"/>
		<OPTIONALTALENT name="Quick Shot"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<OPTIONALTALENT name="Trace Missile"/>
		<OPTIONALTALENT name="Warp Missile"/>
		<DISCIPLINETALENT name="Eagle Eye"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Create Arrow</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Warning Shot"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Dominate Arrow"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<DEFENSE kind="spell"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Blind Fire"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Chameleon"/>
		<OPTIONALTALENT name="Defense"/>
		<OPTIONALTALENT name="Ethereal Weapon"/>
		<OPTIONALTALENT name="Lion Spirit"/>
		<OPTIONALTALENT name="Second Chance"/>
		<OPTIONALTALENT name="True Sight"/>
		<DISCIPLINETALENT name="Multi-Shot"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<KARMASTEP/>
		<ABILITY>Hail of Arrows</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Screaming Arrow"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Wind Bow"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<DEFENSE kind="social"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>caring for ranged weapons; recognize types ranged weapons, ammunition, their creators; Skill: Craft Weapon make ranged weapons, ammunition; (PG p.43)</HALFMAGIC>
</DISCIPLINE>

=== lortas/Earthdawn-Character-Editor/config/disciplines/ED3en/Beastmaster.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DISCIPLINE name="Beastmaster" lang="en" bookref="PG p.44" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../../earthdawndiscipline.xsd">
	<DURABILITY death="7" unconsciousness="6"/>
	<CIRCLE><!-- 1 -->
		<OPTIONALTALENT name="Avoid Blow"/>
		<OPTIONALTALENT name="Climbing"/>
		<OPTIONALTALENT name="Sense Danger"/>
		<OPTIONALTALENT name="Tracking"/>
		<OPTIONALTALENT name="Wilderness Survival"/>
		<DISCIPLINETALENT name="Animal Bond"/>
		<DISCIPLINETALENT name="Claw Shape"/>
		<DISCIPLINETALENT name="Creature Analysis"/>
		<DISCIPLINETALENT name="Karma Ritual"/>
		<DISCIPLINETALENT name="Unarmed Combat"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 2 -->
		<OPTIONALTALENT name="Acrobatic Strike"/>
		<OPTIONALTALENT name="Borrow Sense"/>
		<OPTIONALTALENT name="Durability"/>
		<OPTIONALTALENT name="Frighten Animals"/>
		<OPTIONALTALENT name="Great Leap"/>
		<OPTIONALTALENT name="Haggle"/>
		<OPTIONALTALENT name="Silent Walk"/>
		<OPTIONALTALENT name="Sprint"/>
		<DISCIPLINETALENT name="Dominate Beast"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>
	<CIRCLE><!-- 3 -->
		<DISCIPLINETALENT name="Animal Training"/>
		<TALENTABILITY/>
	</CIRCLE>
	<CIRCLE><!-- 4 -->
		<DISCIPLINETALENT name="Thread Weaving" limitation="Beast Weaving"/>
		<TALENTABILITY/>
		<KARMA spend="Charisma-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 5 -->
		<OPTIONALTALENT name="Animal Companion Durability" limitation="6/5"/>
		<OPTIONALTALENT name="Blood Share"/>
		<OPTIONALTALENT name="Call Animal Companion"/>
		<OPTIONALTALENT name="Empathic Command"/>
		<OPTIONALTALENT name="Lion Heart"/>
		<OPTIONALTALENT name="Poison Resistance"/>
		<OPTIONALTALENT name="Search"/>
		<OPTIONALTALENT name="Tiger Spring"/>
		<DISCIPLINETALENT name="Heal Animal Companion"/>
		<TALENTABILITY/>
		<ABILITY>Primal Urges</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 6 -->
		<DISCIPLINETALENT name="Animal Talk"/>
		<TALENTABILITY/>
		<KARMA spend="Willpower-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 7 -->
		<DISCIPLINETALENT name="Animal Possession"/>
		<TALENTABILITY/>
		<KARMA spend="animal companion Action Test"/>
	</CIRCLE>
	<CIRCLE><!-- 8 -->
		<DISCIPLINETALENT name="Frenzy"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
	</CIRCLE>	
	<CIRCLE><!-- 9 -->
		<OPTIONALTALENT name="Bestial Toughness"/>
		<OPTIONALTALENT name="Cobra Strike"/>
		<OPTIONALTALENT name="Enduring Art"/>
		<OPTIONALTALENT name="Howl"/>
		<OPTIONALTALENT name="Incite Stampede"/>
		<OPTIONALTALENT name="Lion Spirit"/>
		<OPTIONALTALENT name="Safe Path"/>
		<OPTIONALTALENT name="Tame Mount"/>
		<DISCIPLINETALENT name="Chameleon"/>
		<TALENTABILITY/>
		<KARMA spend="Recovery Test"/>
		<ABILITY>Tough Hide</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 10 -->
		<DISCIPLINETALENT name="Animal Leadership"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<CIRCLE><!-- 11 -->
		<DISCIPLINETALENT name="Develop Animal Sense"/>
		<TALENTABILITY/>
		<DEFENSE kind="spell"/>
		<DEFENSE kind="social"/>
		<KARMA spend="Toughness-only Test"/>
	</CIRCLE>
	<CIRCLE><!-- 12 -->
		<DISCIPLINETALENT name="Bestial Resilience"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<INITIATIVE/>
	</CIRCLE>
	<CIRCLE><!-- 13 -->
		<OPTIONALTALENT name="Defense"/>
		<OPTIONALTALENT name="Echo Location"/>
		<OPTIONALTALENT name="First Ring of Perfection"/>
		<OPTIONALTALENT name="Plant Shelter"/>
		<OPTIONALTALENT name="Spirit Strike"/>
		<OPTIONALTALENT name="Trample"/>
		<DISCIPLINETALENT name="Scent Identifier"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<KARMASTEP/>
		<ABILITY>Wild Sense</ABILITY>
	</CIRCLE>
	<CIRCLE><!-- 14 -->
		<DISCIPLINETALENT name="Venom"/>
		<TALENTABILITY/>
		<DEFENSE kind="physical"/>
		<RECOVERYTEST/>
	</CIRCLE>
	<CIRCLE><!-- 15 -->
		<DISCIPLINETALENT name="Astral Web"/>
		<TALENTABILITY/>
		<DEFENSE kind="social"/>
		<DEFENSE kind="spell"/>
	</CIRCLE>
	<KARMARITUAL>Please insert a short description of your Karma Ritual. It have to last for 30 minutes</KARMARITUAL>
	<HALFMAGIC>dealing with/caring for animals beyond described by talents (including animal breeding, first aid, husbandry); recognizing different animals, animal tracks, abnormal behavior among animals/creatures; Skill: Wilderness Survival;(PG p.44)</HALFMAGIC>
</DISCIPLINE>
