=== lortas/Earthdawn-Character-Editor/config/earthdawncapabilities.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/capability" xmlns="http://earthdawn.com/capability" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:element name="CAPABILITIES">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element maxOccurs="unbounded" minOccurs="0" name="SKILL" type="edt:CAPABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="TALENT" type="edt:CAPABILITY_type"/>
			</xs:choice>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED3"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lortas/Earthdawn-Character-Editor/config/capabilities/ED4en/PlayersGuide.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CAPABILITIES lang="en" rulesetversion="ED4" xmlns="http://earthdawn.com/capability" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/capability ../../earthdawncapabilities.xsd">
	<SKILL name="Alchemy" attribute="PER" action="sustained" skilluse="1"/>
	<SKILL name="Physician" attribute="PER" action="sustained" skilluse="1"/>
	<SKILL name="Bribery" attribute="CHA" action="standard" skilluse="1" canimprovised="yes"/>
	<SKILL name="Artist" attribute="CHA" action="sustained" skilluse="1"/>
	<SKILL name="Pilot Boat" attribute="PER" action="sustained" skilluse="1"/>
	<SKILL name="Forgery" attribute="DEX" action="sustained" skilluse="1"/>
	<SKILL name="Flirting" attribute="CHA" action="sustained" skilluse="1" canimprovised="yes"/>
	<SKILL name="Speak Language" attribute="PER" action="standard" skilluse="1"/>
	<SKILL name="Streetwise" attribute="CHA" action="sustained" skilluse="1"/>
	<SKILL name="Craftsman" attribute="DEX" action="sustained" skilluse="1"/>
	<SKILL name="Mapmaking" attribute="PER" action="sustained" skilluse="1"/>
	<SKILL name="Artisan" attribute="CHA" action="sustained" skilluse="1">
		<edt:LIMITATION>Artist</edt:LIMITATION>
		<edt:LIMITATION>Acting</edt:LIMITATION>
		<edt:LIMITATION>Baking</edt:LIMITATION>
		<edt:LIMITATION>Basket Weaving</edt:LIMITATION>
		<edt:LIMITATION>Body Painting</edt:LIMITATION>
		<edt:LIMITATION>Carving</edt:LIMITATION>
		<edt:LIMITATION>Cooking</edt:LIMITATION>
		<edt:LIMITATION>Craftsman</edt:LIMITATION>
		<edt:LIMITATION>Craft Armor</edt:LIMITATION>
		<edt:LIMITATION>Craft Weapon</edt:LIMITATION>
		<edt:LIMITATION>Dancing</edt:LIMITATION>
		<edt:LIMITATION>Embroidery</edt:LIMITATION>
		<edt:LIMITATION>Entertainer</edt:LIMITATION>
		<edt:LIMITATION>Juggling</edt:LIMITATION>
		<edt:LIMITATION>Mapmaking</edt:LIMITATION>
		<edt:LIMITATION>Musician</edt:LIMITATION>
		<edt:LIMITATION>Poetry</edt:LIMITATION>
		<edt:LIMITATION>Rune Carving</edt:LIMITATION>
		<edt:LIMITATION>Sculpting</edt:LIMITATION>
		<edt:LIMITATION>Singing</edt:LIMITATION>
		<edt:LIMITATION>Storytelling</edt:LIMITATION>
		<edt:LIMITATION>Tattooing</edt:LIMITATION>
		<edt:LIMITATION>Wardrobe and Style</edt:LIMITATION>
	</SKILL>
	<SKILL name="Read/Write Language" attribute="PER" action="standard" skilluse="1"/>
	<SKILL name="Craft Armor" attribute="PER" action="sustained" skilluse="1"/>
	<SKILL name="Acting" attribute="CHA" action="sustained" skilluse="1"/>
	<SKILL name="Swimming" attribute="STR" action="standard" skilluse="1" canimprovised="yes"/>
	<SKILL name="Sailing" attribute="DEX" action="sustained" skilluse="1"/>
	<SKILL name="Animal Handling" attribute="WIL" action="standard" skilluse="1" canimprovised="yes"/>
	<SKILL name="Entertainer" attribute="CHA" action="sustained" skilluse="1"/>
	<SKILL name="Seduction" attribute="CHA" action="sustained" skilluse="1" canimprovised="yes"/>
	<SKILL name="Disguise" attribute="PER" action="sustained" skilluse="1"/>
	<SKILL name="Craft Weapon" attribute="PER" action="sustained" skilluse="1"/>
	<SKILL name="Knowledge" attribute="PER" action="standard" skilluse="1">
		<edt:LIMITATION>Alchemy and Potions</edt:LIMITATION>
		<edt:LIMITATION>Ancient Weapons</edt:LIMITATION>
		<edt:LIMITATION>Baking</edt:LIMITATION>
		<edt:LIMITATION>Barsaive History</edt:LIMITATION>
		<edt:LIMITATION>Botany</edt:LIMITATION>
		<edt:LIMITATION>Court Dancing</edt:LIMITATION>
		<edt:LIMITATION>Creature Lore</edt:LIMITATION>
		<edt:LIMITATION>Discipline Lore</edt:LIMITATION>
		<edt:LIMITATION>Farming</edt:LIMITATION>
		<edt:LIMITATION>Horror Lore</edt:LIMITATION>
		<edt:LIMITATION>Legends and Heroes</edt:LIMITATION>
		<edt:LIMITATION>Military Organizations</edt:LIMITATION>
		<edt:LIMITATION>Province History</edt:LIMITATION>
		<edt:LIMITATION>Racial Lore</edt:LIMITATION>
		<edt:LIMITATION>Scourge History</edt:LIMITATION>
		<edt:LIMITATION>Trade Routes</edt:LIMITATION>
		<edt:LIMITATION>Wild Animals</edt:LIMITATION>
	</SKILL>
	<TALENT name="Distract" attribute="CHA" action="simple" strain="1" skilluse="1" canimprovised="yes" />
	<TALENT name="Animal Training" attribute="CHA" action="sustained" skilluse="1"/>
	<TALENT name="Wheeling Defense" attribute="DEX" action="simple" strain="1" skilluse="5"/>
	<TALENT name="Acrobatic Defense" attribute="DEX" action="simple" strain="1" skilluse="1"/>
	<TALENT name="Inspire Others" attribute="CHA" action="standard"/>
	<TALENT name="Arcane Mutterings" attribute="CHA" action="standard" skilluse="1"/>
	<TALENT name="Item History" attribute="PER" action="sustained"/>
	<TALENT name="Astral Interference" attribute="WIL" action="standard" strain="1"/>
	<TALENT name="Astral Sight" attribute="PER" action="simple" strain="1"/>
	<TALENT name="Temper Flesh" attribute="WIL" action="sustained"/>
	<TALENT name="Awareness" attribute="PER" action="simple" skilluse="1" canimprovised="yes"/>
	<TALENT name="Stopping Aim" attribute="CHA" action="standard" strain="1"/>
	<TALENT name="Impressive Display" attribute="na" action="simple" strain="1" skilluse="5"/>
	<TALENT name="Summon" attribute="PER" action="sustained"/>
	<TALENT name="Evidence Analysis" attribute="PER" action="sustained" strain="1" skilluse="5"/>
	<TALENT name="True Shot" attribute="na" action="free" strain="2"/>
	<TALENT name="Lasting Impression" attribute="CHA" action="standard"/>
	<TALENT name="Claw Frenzy" attribute="DEX" action="standard" strain="1 (s. Text)"/>
	<TALENT name="Flame Arrow" attribute="WIL" action="free" strain="1"/>
	<TALENT name="Book Memory" attribute="WIL" action="standard"/>
	<TALENT name="Diplomacy" attribute="CHA" action="sustained" skilluse="1"/>
	<TALENT name="Double Charge" attribute="DEX" action="simple" strain="1"/>
	<TALENT name="Iron Constitution" attribute="TOU" action="free"/>
	<TALENT name="Steel Thought" attribute="WIL" action="free" strain="4"/>
	<TALENT name="Graceful Exit" attribute="CHA" action="standard" skilluse="1"/>
	<TALENT name="Elemental Hold" attribute="WIL" action="standard" strain="1"/>
	<TALENT name="Elemental Tongues" attribute="PER" action="standard" strain="1"/>
	<TALENT name="Empathic Sense" attribute="CHA" action="standard" strain="1 (s. Text)"/>
	<TALENT name="Disarm" attribute="DEX" action="standard" strain="1" skilluse="5"/>
	<TALENT name="Earth Skin" attribute="TOU" action="standard"/>
	<TALENT name="First Impression" attribute="CHA" action="standard" skilluse="1"/>
	<TALENT name="Enhanced Matrix" attribute="na" action="na"/>
	<TALENT name="Etiquette" attribute="CHA" action="sustained" skilluse="1" canimprovised="yes"/>
	<TALENT name="Hold Thread" attribute="WIL" action="simple" strain="1 (s. Text)"/>
	<TALENT name="Thread Weaving" attribute="PER" action="standard"/>
	<TALENT name="Disarm Trap" attribute="DEX" action="standard" strain="1" skilluse="1"/> 
	<TALENT name="Haggle" attribute="CHA" action="sustained" skilluse="1" canimprovised="yes"/>
	<TALENT name="Fireblood" attribute="TOU" action="standard"/>
	<TALENT name="Fast Hand" attribute="DEX" action="standard" strain="1" skilluse="5"/>
	<TALENT name="Suppress Curse" attribute="WIL" action="standard" strain="1"/>
	<TALENT name="Research" attribute="PER" action="sustained" skilluse="1" canimprovised="yes"/>
	<TALENT name="Speak Language" attribute="PER" action="standard" strain="1 (s. Text)"/>
	<TALENT name="Leadership" attribute="CHA" action="sustained" skilluse="5"/>
	<TALENT name="Fearsome Charge" attribute="CHA" action="simple" strain="2"/>
	<TALENT name="Thought Link" attribute="PER" action="standard" strain="1"/>
	<TALENT name="Danger Sense" attribute="DEX" action="free" strain="1" skilluse="1"/>
	<TALENT name="Emotion Song" attribute="CHA" action="sustained" skilluse="1"/>
	<TALENT name="Conceal Object" attribute="DEX" action="standard" strain="1" skilluse="5"/>
	<TALENT name="Spirit Hold" attribute="WIL" action="standard" strain="1"/>
	<TALENT name="Spirit Mount" attribute="PER" action="standard" strain="1"/>
	<TALENT name="Spirit Talk" attribute="PER" action="standard" strain="1"/>
	<TALENT name="Winning Smile" attribute="CHA" action="standard"/>
	<TALENT name="Bank Shot" attribute="DEX" action="simple" strain="1"/>
	<TALENT name="Down Strike" attribute="STR" action="free" strain="1"/>
	<TALENT name="Tenacious Weave" attribute="WIL" action="free" strain="1"/>
	<TALENT name="Fire Heal" attribute="WIL" action="sustained"/>
	<TALENT name="Stealthy Stride" attribute="DEX" action="simple" skilluse="1"/>
	<TALENT name="Heartening Laugh" attribute="CHA" action="simple" strain="1" skilluse="1"/>
	<TALENT name="Avoid Blow" attribute="DEX" action="free" strain="1" skilluse="1"/>
	<TALENT name="Wood Skin" attribute="TOU" action="standard"/>
	<TALENT name="Hypnotize" attribute="CHA" action="sustained" strain="1" skilluse="5"/>
	<TALENT name="False Sight" attribute="WIL" action="free" strain="1"/>
	<TALENT name="Battle Shout" attribute="CHA" action="simple" strain="1" skilluse="1"/>
	<TALENT name="Anticipate Blow" attribute="PER" action="simple" strain="1" skilluse="1"/>
	<TALENT name="Climbing" attribute="DEX" action="standard" skilluse="1" canimprovised="yes"/>
	<TALENT name="Blade Juggle" attribute="DEX" action="standard" strain="1 (s. Text)" skilluse="5"/>
	<TALENT name="Cobra Strike" attribute="DEX" action="free" strain="2"/>
	<TALENT name="Mystic Pursuit" attribute="PER" action="standard" strain="2"/>
	<TALENT name="Conversation" attribute="CHA" action="sustained" skilluse="1" canimprovised="yes"/>
	<TALENT name="Claw Shape" attribute="STR" bonus="3" action="simple"/>
	<TALENT name="Orbiting Spy" attribute="PER" action="standard"/>
	<TALENT name="Trick Riding" attribute="DEX" action="simple" strain="1" skilluse="1"/>
	<TALENT name="Lifesight" attribute="PER" action="simple" strain="1"/>
	<TALENT name="Read and Write Language" attribute="PER" action="sustained" strain="1 (s. Text)"/>
	<TALENT name="Life Check" attribute="TOU" action="free"/>
