=== lortas/Earthdawn-Character-Editor/config/earthdawntranslation.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/translation" xmlns="http://earthdawn.com/translation" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="translationlabel_type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="lang" type="edt:language_type" use="required"/>
				<xs:attribute name="acronym" type="edt:acronym_type" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="TRANSLATION_type">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="1" name="LABEL" type="translationlabel_type"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NAMES_ATTRIBUTE_type">
		<xs:attribute name="attribute" type="edt:ATTRIBUTE_name_type" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="acronym" type="edt:acronym_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="NAMES_ATTRIBUTES_type">
		<xs:sequence>
			<xs:element name="ATTRIBUTE" type="NAMES_ATTRIBUTE_type" minOccurs="6" maxOccurs="6"/>
		</xs:sequence>
		<xs:attribute name="lang" type="edt:language_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="NAMES_ACTION_type">
		<xs:attribute name="action" type="edt:action_type" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="acronym" type="edt:acronym_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="NAMES_ACTIONS_type">
		<xs:sequence>
			<xs:element name="ACTION" type="NAMES_ACTION_type" minOccurs="5" maxOccurs="5"/>
		</xs:sequence>
		<xs:attribute name="lang" type="edt:language_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="NAME_SPELLWEAVING_type">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="SPELLKIND" type="NAME_SPELLKIND_type"/>
		</xs:sequence>
		<xs:attribute name="lang" type="edt:language_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="NAME_SPELLKIND_type">
		<xs:attribute name="weaving" type="xs:string" use="required"/>
		<xs:attribute name="type" type="edt:spellkind_type" use="required"/>
	</xs:complexType>
	<xs:element name="TRANSLATIONS">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element minOccurs="1" maxOccurs="unbounded" name="ATTRIBUTES" type="NAMES_ATTRIBUTES_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="ACTIONS" type="NAMES_ACTIONS_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="DURABILITY" type="TRANSLATION_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="VERSATILITY" type="TRANSLATION_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="KARMARUTUAL" type="TRANSLATION_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="ARTISAN" type="TRANSLATION_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="KNOWLEDGE" type="TRANSLATION_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="QUESTORTALENT" type="TRANSLATION_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="THREADWEAVING" type="TRANSLATION_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="LANGUAGESKILLSPEAK" type="TRANSLATION_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="LANGUAGESKILLREADWRITE" type="TRANSLATION_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="SPELLWEAVING" type="NAME_SPELLWEAVING_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="CAPABILITY" type="TRANSLATION_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="SPELL" type="TRANSLATION_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="DISCIPLINE" type="TRANSLATION_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="ITEM" type="TRANSLATION_type"/>
			</xs:sequence>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lortas/Earthdawn-Character-Editor/config/translation/ED4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<TRANSLATIONS rulesetversion="ED4" xmlns="http://earthdawn.com/translation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://earthdawn.com/translation ../earthdawntranslation.xsd">
	<ATTRIBUTES lang="de">
		<ATTRIBUTE attribute="DEX" acronym="GES" name="Geschicklichkeit"/>
		<ATTRIBUTE attribute="STR" acronym="STÄ" name="Stärke"/>
		<ATTRIBUTE attribute="TOU" acronym="ZÄH" name="Zähigkeit"/>
		<ATTRIBUTE attribute="PER" acronym="WAH" name="Wahrnehmung"/>
		<ATTRIBUTE attribute="WIL" acronym="WIL" name="Willenskraft"/>
		<ATTRIBUTE attribute="CHA" acronym="CHA" name="Charisma"/>
	</ATTRIBUTES>
	<ATTRIBUTES lang="en">
		<ATTRIBUTE attribute="DEX" acronym="DEX" name="Dexterity"/>
		<ATTRIBUTE attribute="STR" acronym="STR" name="Strength"/>
		<ATTRIBUTE attribute="TOU" acronym="TOU" name="Toughness"/>
		<ATTRIBUTE attribute="PER" acronym="PER" name="Perception"/>
		<ATTRIBUTE attribute="WIL" acronym="WIL" name="Willenpower"/>
		<ATTRIBUTE attribute="CHA" acronym="CHA" name="Charisma"/>
	</ATTRIBUTES>
	<ACTIONS lang="de">
		<ACTION action="sustained" acronym="and" name="Andauernd"/>
		<ACTION action="standard" acronym="std" name="Standard"/>
		<ACTION action="simple" acronym="einf" name="Einfach"/>
		<ACTION action="free" acronym="frei" name="Frei"/>
		<ACTION action="na" acronym="nv" name="Nicht Verfügbar"/>
	</ACTIONS>
	<ACTIONS lang="en">
		<ACTION action="sustained" acronym="sust" name="Sustained"/>
		<ACTION action="standard" acronym="std" name="Standard"/>
		<ACTION action="simple" acronym="smpl" name="Simple"/>
		<ACTION action="free" acronym="free" name="Free"/>
		<ACTION action="na" acronym="na" name="Not Avialabel"/>
	</ACTIONS>
	<DURABILITY>
		<LABEL lang="de">Unempfindlichkeit</LABEL>
		<LABEL lang="en">Durability</LABEL>
	</DURABILITY>
	<VERSATILITY>
		<LABEL lang="de">Vielseitigkeit</LABEL>
		<LABEL lang="en">Versatility</LABEL>
	</VERSATILITY>
	<KARMARUTUAL>
		<LABEL lang="de">Karma Ritual</LABEL>
		<LABEL lang="en">Karma Ritual</LABEL>
	</KARMARUTUAL>
	<ARTISAN>
		<LABEL lang="de" acronym="K" >Kunsthandwerk</LABEL>
		<LABEL lang="en" acronym="A">Artisan</LABEL>
	</ARTISAN>
	<KNOWLEDGE>
		<LABEL lang="de" acronym="W">Wissen</LABEL>
		<LABEL lang="en" acronym="K">Knowledge</LABEL>
	</KNOWLEDGE>
	<QUESTORTALENT>
		<LABEL lang="de">Questor</LABEL>
		<LABEL lang="en">Questor</LABEL>
	</QUESTORTALENT>
	<THREADWEAVING>
		<LABEL lang="en">Thread Weaving</LABEL>
		<LABEL lang="de">Fadenweben</LABEL>
	</THREADWEAVING>
	<LANGUAGESKILLSPEAK>
		<LABEL lang="en">Speak Language</LABEL>
		<LABEL lang="de">Fremdsprachen</LABEL>
	</LANGUAGESKILLSPEAK>
	<LANGUAGESKILLREADWRITE>
		<LABEL lang="en">Read/Write Language</LABEL>
		<LABEL lang="de">Lesen/Schreiben</LABEL>
	</LANGUAGESKILLREADWRITE>
	<SPELLWEAVING lang="en">
		<SPELLKIND type="elemental" acronym="ele" weaving="Elementalism"/>
		<SPELLKIND type="illusion"  acronym="ilu" weaving="Illusionism"/>
		<SPELLKIND type="nether"    acronym="nth" weaving="Nethermancy"/>
		<SPELLKIND type="shaman"    acronym="shm" weaving="Shamanism"/>
		<SPELLKIND type="sorcery"   acronym="sor" weaving="Sorcery"/>
		<SPELLKIND type="wizard"    acronym="wiz" weaving="Wizardry"/>
		<SPELLKIND type="trickster" acronym="tri" weaving="Trickstry"/>
		<SPELLELEMENT element="fire" acronym="fi" name="Fire"/>
		<SPELLELEMENT element="water" acronym="w" name="Water"/>
		<SPELLELEMENT element="undefined" acronym="-" name="Undefined"/>
		<SPELLELEMENT element="wood" acronym="w" name="Wood"/>
		<SPELLELEMENT element="earth" acronym="e" name="Earth"/>
		<SPELLELEMENT element="air" acronym="a" name="Air"/>
		<SPELLELEMENT element="illusion" acronym="i" name="Illusion"/>
		<SPELLELEMENT element="fear" acronym="fe" name="Fear"/>
		<SPELLELEMENT element="orichalcum" acronym="or" name="orichalcum"/>
		<SPELLELEMENT element="earth-metal" acronym="em" name="Earth-Metal"/>
		<SPELLELEMENT element="water-acid" acronym="wa" name="Water-Acid"/>
		<SPELLELEMENT element="water-cold" acronym="wc" name="Water-Cold"/>
		<SPELLELEMENT element="air-electric" acronym="ae" name="Air-Electric"/>
		<SPELLELEMENT element="figment" acronym="fg" name="Figment"/>
		<SPELLELEMENT element="spirit" acronym="sp" name="Spirit"/>
		<SPELLELEMENT element="binding" acronym="b" name="Binding"/>
		<SPELLELEMENT element="summoning" acronym="su" name="Summoning"/>
		<SPELLELEMENT element="fate" acronym="fa" name="Fate"/>
	</SPELLWEAVING>
	<SPELLWEAVING lang="de">
		<SPELLKIND type="elemental" acronym="ele" weaving="Elementarismus"/>
		<SPELLKIND type="illusion"  acronym="ilu" weaving="Illusionismus"/>
		<SPELLKIND type="nether"    acronym="gei" weaving="Geisterbeschwörung"/>
		<SPELLKIND type="shaman"    acronym="shm" weaving="Schamanismus"/>
		<SPELLKIND type="sorcery"   acronym="hex" weaving="Hexerei"/>
		<SPELLKIND type="wizard"    acronym="mag" weaving="Magie"/>
		<SPELLKIND type="trickster" acronym="tri" weaving="Tricksen"/>
		<SPELLELEMENT element="fire" acronym="fe" name="Feuer"/>
		<SPELLELEMENT element="water" acronym="w" name="Wasser"/>
		<SPELLELEMENT element="undefined" acronym="-" name="Undefiniert"/>
		<SPELLELEMENT element="wood" acronym="h" name="Holz"/>
		<SPELLELEMENT element="earth" acronym="e" name="Erde"/>
		<SPELLELEMENT element="air" acronym="l" name="Luft"/>
		<SPELLELEMENT element="illusion" acronym="i" name="Illusion"/>
		<SPELLELEMENT element="fear" acronym="fu" name="Furcht"/>
		<SPELLELEMENT element="orichalcum" acronym="or" name="Orichalkum"/>
		<SPELLELEMENT element="earth-metal" acronym="em" name="Erd-Metal"/>
		<SPELLELEMENT element="water-acid" acronym="ws" name="Wasser-Säure"/>
		<SPELLELEMENT element="water-cold" acronym="wk" name="Wasse-Kälte"/>
		<SPELLELEMENT element="air-electric" acronym="le" name="Luft-Elektrizität"/>
		<SPELLELEMENT element="figment" acronym="ei" name="Einbindung"/>
		<SPELLELEMENT element="spirit" acronym="g" name="Geist"/>
		<SPELLELEMENT element="binding" acronym="bi" name="Bindung"/>
		<SPELLELEMENT element="summoning" acronym="be" name="Beschwörung"/>
		<SPELLELEMENT element="fate" acronym="fü" name="Fügung"/>
	</SPELLWEAVING>
	<CAPABILITY>
		<LABEL lang="en">Distract</LABEL>
		<LABEL lang="de">Ablenken</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Animal Training</LABEL>
		<LABEL lang="de">Abrichten</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Wheeling Defense</LABEL>
		<LABEL lang="de">Abwehrkreis</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Acrobatic Defense</LABEL>
		<LABEL lang="de">Akrobatische Verteidigung</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Alchemy</LABEL>
		<LABEL lang="de">Alchemie</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Inspire Others</LABEL>
		<LABEL lang="de">Andere Inspirieren</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Arcane Mutterings</LABEL>
		<LABEL lang="de">Arkanes Gefasel</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Item History</LABEL>
		<LABEL lang="de">Artefaktgeschichte</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Physician</LABEL>
		<LABEL lang="de">Arzt</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Astral Interference</LABEL>
		<LABEL lang="de">Astrale Interferenz</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Astral Sight</LABEL>
		<LABEL lang="de">Astralsicht</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Awareness</LABEL>
		<LABEL lang="de">Aufmerksamkeit</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Stopping Aim</LABEL>
		<LABEL lang="de">Bannmarkierung</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Impressive Display</LABEL>
		<LABEL lang="de">Beeindrucken</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Summon</LABEL>
		<LABEL lang="de">Beschwören</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Bribery</LABEL>
		<LABEL lang="de">Bestechung</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Evidence Analysis</LABEL>
		<LABEL lang="de">Beweisanalyse</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Artist</LABEL>
		<LABEL lang="de">Bildende Kunst</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">True Shot</LABEL>
		<LABEL lang="de">Blattschuss</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Lasting Impression</LABEL>
		<LABEL lang="de">Bleibender Eindruck</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Claw Frenzy</LABEL>
		<LABEL lang="de">Blutige Krallen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Pilot Boat</LABEL>
		<LABEL lang="de">Boot Steuern</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Flame Arrow</LABEL>
		<LABEL lang="de">Brandpfeil</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Book Memory</LABEL>
		<LABEL lang="de">Büchergedächtnis</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Diplomacy</LABEL>
		<LABEL lang="de">Diplomatie</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Double-Charge</LABEL>
		<LABEL lang="de">Doppelter Sturmangriff</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Iron Constitution</LABEL>
		<LABEL lang="de">Eiserne Konstitution</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Steel Thought</LABEL>
		<LABEL lang="de">Eiserner Wille</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Graceful Exit</LABEL>
		<LABEL lang="de">Eleganter Abgang</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Elemental Hold</LABEL>
		<LABEL lang="de">Elementarbann</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Elemental Tongues</LABEL>
		<LABEL lang="de">Elementarsprachen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Empathic Sense</LABEL>
		<LABEL lang="de">Empathische Wahrnehmung</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Disarm</LABEL>
		<LABEL lang="de">Entwaffnen</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">Earth Skin</LABEL>
		<LABEL lang="de">Erdhaut</LABEL>
	</CAPABILITY>
	<CAPABILITY>
		<LABEL lang="en">First Impression</LABEL>
