=== lortas/Earthdawn-Character-Editor/config/earthdawnknacks.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/knack" xmlns="http://earthdawn.com/knack" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="KNACKRACE_type">
				<xs:attribute name="name" type="xs:string" use="required"/>
				<xs:attribute name="prerequisite" type="edt:prerequisitekind_type" default="restriction"/>
	</xs:complexType>
	<xs:complexType name="KNACKBASECAPABILITY_type">
				<xs:attribute name="type" type="edt:capabilitytype_type" use="required"/>
				<xs:attribute name="name" type="xs:string" use="required"/>
				<xs:attribute name="limitation" type="xs:string" default=""/>
				<xs:attribute name="minrank" type="edt:unsigned_int" default="0"/>
	</xs:complexType>
	<xs:complexType name="KNACKDISCIPLINE_type">
				<xs:attribute name="name" type="xs:string" default="*"/>
				<xs:attribute name="circle" type="edt:unsigned_int" default="1"/>
				<xs:attribute name="prerequisite" type="edt:prerequisitekind_type" default="restriction"/>
	</xs:complexType>
	<xs:complexType name="KNACKATTRIBUTE_type">
				<xs:attribute name="name" type="edt:ATTRIBUTE_name_type" use="required"/>
				<xs:attribute name="min" type="edt:unsigned_int" default="1"/>
				<xs:attribute name="max" type="edt:unsigned_int" default="0"/>
				<xs:attribute name="prerequisite" type="edt:prerequisitekind_type" default="restriction"/>
	</xs:complexType>
	<xs:complexType name="KNACKCAPABILITY_type">
				<xs:attribute name="name" type="xs:string" use="required"/>
				<xs:attribute name="limitation" type="xs:string" default=""/>
				<xs:attribute name="minrank" type="edt:unsigned_int" default="1"/>
				<xs:attribute name="maxrank" type="edt:unsigned_int" default="0"/>
				<xs:attribute name="prerequisite" type="edt:prerequisitekind_type" default="restriction"/>
                                <xs:attribute name="prerequisiteoption" type="edt:prerequisiteoptionpairkind_type" default="na"/>
	</xs:complexType>
	<xs:complexType name="KNACKOTHERKNACK_type">
				<xs:attribute name="name" type="xs:string" default="*"/>
				<xs:attribute name="prerequisite" type="edt:prerequisitekind_type" default="restriction"/>
	</xs:complexType>
	<xs:complexType name="KNACKDEFINITION_type">
		<xs:complexContent>
			<xs:extension base="edt:KNACKBASE_type">
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="1" name="BASE" type="KNACKBASECAPABILITY_type"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="KNACK" type="KNACKOTHERKNACK_type"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="DISCIPLINE" type="KNACKDISCIPLINE_type"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="TALENT" type="KNACKCAPABILITY_type"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="SKILL" type="KNACKCAPABILITY_type"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="RACE" type="KNACKRACE_type"/>
					<xs:element maxOccurs="unbounded" minOccurs="0" name="ATTRIBUTE" type="KNACKATTRIBUTE_type"/>
				</xs:sequence>
				<xs:attribute name="skilluse" type="edt:unsigned_int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="KNACKS">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="KNACK" type="KNACKDEFINITION_type"/>
			</xs:sequence>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="rulesetversion" type="edt:rulesetversion_type" default="ED3"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lortas/Earthdawn-Character-Editor/config/knacks/ED3en/PlayersCompendium.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<KNACKS lang="en" xmlns="http://earthdawn.com/knack" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://earthdawn.com/knack ../../earthdawnknacks.xsd">
	<KNACK name="Adept's Best Friend"           minrank="6"  strain="3"     bookref="PC p.120"><BASE type="talent" name="Tracking"/>                                   </KNACK>
	<KNACK name="Air Conditioning"              minrank="6"  strain="2"     bookref="PC p.120"><BASE type="talent" name="Temperature"/>                                </KNACK>	
	<KNACK name="Air Legs"                      minrank="4"  strain="2"     bookref="PC p.121"><BASE type="talent" name="Air Sailing"/>                                </KNACK>
	<KNACK name="Air Mount"                     minrank="13" strain="6"     bookref="PC p.121"><BASE type="talent" name="Spirit Mount"/>                               </KNACK>
	<KNACK name="Anchored Spell"                minrank="8"  blood="1"      bookref="PC p.121"><BASE type="talent" name="Spellcasting"/>                               </KNACK>
	<KNACK name="Angelic Appearance"            minrank="7"  strain="1"     bookref="PC p.121"><BASE type="talent" name="Disguise Self"/>                              </KNACK>
	<KNACK name="Animal's Best Friend"          minrank="6"  strain="4"     bookref="PC p.121"><BASE type="talent" name="Tracking"/>                                   </KNACK>
	<KNACK name="Arcane Curses"                 minrank="7"  strain="1"     bookref="PC p.121"><BASE type="talent" name="Arcane Mutterings"/>                          </KNACK>
	<KNACK name="Armor Beater"                  minrank="10" strain="3"     bookref="PC p.122"><BASE type="talent" name="Melee Weapons"/>                              </KNACK>
	<KNACK name="Arrow Cutting"                 minrank="9"  strain="2"     bookref="PC p.122"><BASE type="talent" name="Parry"/>                                      </KNACK>
	<KNACK name="Arrow Stop"                    minrank="7"  strain="2"     bookref="PC p.122"><BASE type="talent" name="Impressive Shot"/>                            </KNACK>
	<KNACK name="Assault"                       minrank="8"  strain="4"     bookref="PC p.122"><BASE type="talent" name="Air Sailing"/>                                </KNACK>
	<KNACK name="Astral Spy"                    minrank="9"  strain="1+"    bookref="PC p.122"><BASE type="talent" name="Orbiting Spy"/>                               </KNACK>
	<KNACK name="Astral Tracking"               minrank="9"  strain="2"     bookref="PC p.122"><BASE type="talent" name="Tracking"/>                                   </KNACK>
	<KNACK name="Attribute Pattern"             minrank="15" strain="2"     bookref="PC p.122"><BASE type="talent" name="Thread Weaving"/>                             </KNACK>
	<KNACK name="Backbiter"                     minrank="7"  strain="3"     bookref="PC p.122"><BASE type="talent" name="Bank Shot"/>                                  </KNACK>
	<KNACK name="Bind Spirit"                   minrank="6"  strain="2"     bookref="PC p.122"><BASE type="talent" name="Summon"/>                                     </KNACK>
	<KNACK name="Bless Ally"                    minrank="12" strain="4"     bookref="PC p.123"><BASE type="talent" name="Second Chance"/>                              </KNACK>
	<KNACK name="Blood Compass"                 minrank="9"  strain="3"     bookref="PC p.123"><BASE type="talent" name="Bone Compass"/>                               </KNACK>
	<KNACK name="Boarding Action"               minrank="8"  strain="4"     bookref="PC p.123"><BASE type="talent" name="Air Sailing"/>                                </KNACK>
	<KNACK name="Bounce"                        minrank="9"  strain="2"     bookref="PC p.123"><BASE type="talent" name="Avoid Blow"/>                                 </KNACK>
	<KNACK name="Braiding Threads"              minrank="7"  strain="2"     bookref="PC p.123"><BASE type="talent" name="Thread Weaving"/>                             </KNACK>
	<KNACK name="By the Fingernails"            minrank="7"  strain="4"     bookref="PC p.123"><BASE type="talent" name="Climbing"/>                                   </KNACK>
	<KNACK name="Calm Herd"                     minrank="8"  strain="2"     bookref="PC p.123"><BASE type="talent" name="Incite Stampede"/>                            </KNACK>
	<KNACK name="Claw Riposte"                  minrank="9"  strain="3"     bookref="PC p.123"><BASE type="talent" name="Riposte"/>                                    </KNACK>
	<KNACK name="Claw Tool"                     minrank="4"  strain="2/min" bookref="PC p.123"><BASE type="talent" name="Claw Shape"/>                                 </KNACK>
	<KNACK name="Cosmetics"                     minrank="9"  strain="2+"    bookref="PC p.123"><BASE type="talent" name="Fire Heal"/>                                  </KNACK>
	<KNACK name="Covet Item"                    minrank="7"  strain="4"     bookref="PC p.123"><BASE type="talent" name="Haggle"/>                                     </KNACK>
	<KNACK name="Create Orichalcum"             minrank="11" strain="2"     bookref="PC p.123"><BASE type="talent" name="Thread Weaving" limitation="Elementalism"   /></KNACK>
	<KNACK name="Create Armored Matrix Object"  minrank="12" strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Elementalism"   /></KNACK>
	<KNACK name="Create Armored Matrix Object"  minrank="12" strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Illusionism"    /></KNACK>
	<KNACK name="Create Armored Matrix Object"  minrank="12" strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Nethermancy"    /></KNACK>
	<KNACK name="Create Armored Matrix Object"  minrank="12" strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Shamanism"      /></KNACK>
	<KNACK name="Create Armored Matrix Object"  minrank="12" strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Sorcery"        /></KNACK>
	<KNACK name="Create Armored Matrix Object"  minrank="12" strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Wizardry"       /></KNACK>
	<KNACK name="Create Common Magic Item"      minrank="5"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Elementalism"   /></KNACK>
	<KNACK name="Create Common Magic Item"      minrank="5"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Illusionism"    /></KNACK>
	<KNACK name="Create Common Magic Item"      minrank="5"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Nethermancy"    /></KNACK>
	<KNACK name="Create Common Magic Item"      minrank="5"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Shamanism"      /></KNACK>
	<KNACK name="Create Common Magic Item"      minrank="5"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Sorcery"        /></KNACK>
	<KNACK name="Create Common Magic Item"      minrank="5"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Thread Smithing"/></KNACK>
	<KNACK name="Create Common Magic Item"      minrank="5"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Wizardry"       /></KNACK>
	<KNACK name="Create Enhanced Matrix Object" minrank="8"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Elementalism"   /></KNACK>
	<KNACK name="Create Enhanced Matrix Object" minrank="8"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Illusionism"    /></KNACK>
	<KNACK name="Create Enhanced Matrix Object" minrank="8"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Nethermancy"    /></KNACK>
	<KNACK name="Create Enhanced Matrix Object" minrank="8"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Shamanism"      /></KNACK>
	<KNACK name="Create Enhanced Matrix Object" minrank="8"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Sorcery"        /></KNACK>
	<KNACK name="Create Enhanced Matrix Object" minrank="8"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Wizardry"       /></KNACK>
	<KNACK name="Create Shared Matrix Object"   minrank="15" strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Elementalism"   /></KNACK>
	<KNACK name="Create Shared Matrix Object"   minrank="15" strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Illusionism"    /></KNACK>
	<KNACK name="Create Shared Matrix Object"   minrank="15" strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Nethermancy"    /></KNACK>
	<KNACK name="Create Shared Matrix Object"   minrank="15" strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Shamanism"      /></KNACK>
	<KNACK name="Create Shared Matrix Object"   minrank="15" strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Sorcery"        /></KNACK>
	<KNACK name="Create Shared Matrix Object"   minrank="15" strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Wizardry"       /></KNACK>
	<KNACK name="Create Spell Matrix Object"    minrank="5"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Elementalism"   /></KNACK>
	<KNACK name="Create Spell Matrix Object"    minrank="5"  strain="2"     bookref="PC p.124"><BASE type="talent" name="Thread Weaving" limitation="Illusionism"    /></KNACK>
